# Introdução {-#Introdução}

Os usos antrópicos dos recursos ambientais têm moldado em escala global os padrões espaciais dos ecossistemas, determinando a magnitude da perda de biodiversidade e de serviços ecossistêmicos e tornando raros os locais no planeta que não sofrem algum grau de influência humana [@Sanderson2002; @Vorosmarty2010]. Para a maioria dos ecossistemas, as atividades humanas que se caracterizam como as principais ameaças a curto prazo são a expansão da agricultura e das áreas urbanas [@Allan2004a; @FAO2010]. A expansão da malha rodoviária é também um fator de ameaça, seja pela implantação das rodovias em si, seja pelo acesso que elas proporcionam a locais até então inalterados [@Trombulak2000; @Sanderson2002; @Angermeier2004a; @Laurance2013]. No Brasil, a previsão é de que, até 2024, haja um aumento no uso da terra correspondente a 20% sobre a área média durante os anos de 2012 a 2014, especialmente para cultivos de oleaginosas, cereais, cana e algodão [@Vinet2016]. Podemos esperar, consequentemente, um efeito em cascata no sentido do investimento em infraestrutura e matéria-prima para produção e distribuição desta atividade.

Devido a essa dinâmica em escala regional de expansão da ação humana, a aplicação dos princípios de planejamento sistemático para conservação tem crescido, com o intuito de localizar áreas prioritárias de forma organizada e objetiva, contemplando o maior número de aspectos bióticos e abióticos que definam interesse para conservação, como por exemplo, áreas hipoteticamente intocadas ou pouco degradadas [@Margules2000; @Linke2011c; @Lourival2011a], áreas de biodiversidade elevada ou biogeograficamente representativas, áreas importantes para serviços ecossistêmicos, ou, áreas fortemente pressionadas e que reúnam alguma das características anteriores [@Myers2000; @Brooks2006]. O planejamento sistemático de conservação tem como característica principal as escolhas claras e explícitas no processo do planejamento tanto no que diz respeito as características dos componentes da biodiversidade a serem usados no processo de planejamento, quanto nos objetivos de conservação, sempre que possível traduzidos em metas quantitativas e operacionais [@Pressey2007]. O uso dos sistemas de informação geográfica (SIG) facilita a visualização dessas alterações no espaço permitindo maior eficiência e sistematização nas relações das alterações na cobertura do solo na biodiversidade e suas consequências para o planejamento territorial [@Tulloch2015]. Avaliações em escala espacial ampla, de unidades de paisagem - como bacias hidrográficas - são necessárias para gerenciamento do território, tomada de decisão e manejo da fauna porque é a escala em que os efeitos cumulativos dos impactos ficam evidentes, tornando as causas da degradação ambiental mais facilmente observáveis [@ONeill1997; @Wiens2002; @Stein2002a]. 

Quando o interesse de conservação está na biodiversidade aquática de água-doce, as unidades espaciais empregadas na análise podem ser rios, riachos ou bacias hidrográficas. Rios e riachos são geralmente afetados por múltiplos distúrbios que se acumulam e interagem no espaço e no tempo, tornando o entendimento da resposta para determinadas ameaças uma tarefa complexa [@Allan2004a]. É importante ressaltar que estes indicadores de pressão representam uma degradação potencial do ambiente e não da degradação efetiva, a qual é resultado da interação de fatores cujo histórico, intensidade, frequência e efeito variam regionalmente. De posse dessas informações, é possível determinar quais unidades de paisagem recebem maior pressão por atividades antrópicas e assumir que aquelas onde há ausência de pressão ambiental - ou pelo menos aquelas menos pressionadas - sejam tratadas como sítios de referência para comparações dos padrões observados ao longo de gradientes de pressão [@Stoddard2006]. A condição destas unidades pode ser definida como a similaridade do sítio avaliado em relação a um conjunto de sítios menos degradados, levando em consideração características bióticas (conjunto de indicadores, como o número de espécies intolerantes, riqueza e composição de espécies; espécies ameaçadas, etc.) [@Stoddard2006; @Allan2013].

Normalmente assume-se que existe uma relação negativa entre diversidade de espécies e pressão ambiental como fundamento para uso de mapas de pressão na priorização de áreas para conservação e que a proteção de determinado conjunto de características abióticas (mais fáceis de quantificar) consequentemente conservará o conjunto de espécies que ocorram neste local [@Stein2002a; @Khoury2011a; @Tulloch2015]. 
<!-- \%como fazer pra ficar na ordem cronológica ou alfabética automaticamente? -->
Entretanto, esse é um pressuposto que deve ser validado para que o objetivo de conservação seja efetivamente alcançado. Alguns trabalhos não consideram dados bióticos na determinação de locais que sirvam como referência para conservação com menor influência antrópica [@Sanderson2002], e outros consideram os alvos de conservação ao dar pesos aos indicadores relacionados ao efeito potencial que eles tem sobre as espécies [@Stein2002a; @Heiner2011a], mas poucos são os que validam esta relação com dados de campo para mostrar que ela verdadeiramente existe [@Esselman2011b; @Ligeiro2013]. A comparação de dados de campo aumenta a eficiência das ações de conservação ao esclarecer a relação do objetivo de conservação (por exemplo, diversidade) e os fatores de pressão [@Tulloch2013].

## A conservação de riachos nos campos do Pampa {-}

Os ambientes campestres são bastante sensíveis às mudanças da cobertura do solo, não importa em que região do planeta estejam localizados [@Sala2000a; @Andrade2015a]. Embora sejam ricos em número de espécies [@Overbeck2005; @Overbeck2006; @Wilson2012] e ofereçam inúmeros serviços ecossistêmicos, com frequência são ignorados como alvo de conservação. As regiões campestres localizadas na metade sul do Rio Grande do Sul fazem parte do chamado Pampa, bioma de campos que inclui ainda partes do Uruguai e Argentina [@Overbeck2007a]. A proporção de remanescentes de campos é de aproximadamente 50% em relação a sua área original no Rio Grande do Sul, por conta da acelerada conversão do solo para, principalmente, a agricultura e a silvicultura [@Cordeiro2009a] e apenas 0,33% dos campos estão atualmente protegidos em unidades de proteção integral [@Overbeck2007a].

Os principais usos presentes no bioma Pampa são pecuária e agricultura, que podem aparecer em associação por rodízio de culturas [@Nabinger2000]. A agricultura apresentou crescimento mais intenso nas últimas décadas, especialmente pelos cultivos de arroz, milho, soja, trigo e silvicultura [@IBGE2015], atividades que contam com incentivo de empresas privadas e do governo, com consequente diminuição das áreas de vegetação nativa [@Nabinger2000; @Overbeck2007a; @Cordeiro2009a]. A construção de açudes para dessedentação animal e para irrigação da plantações é uma consequência dessas atividades econômicas, e representam grave influência na fragmentação da rede hidrográfica [@Clavero2011], uma vez que nem sempre necessitam de licenciamento ambiental prévio para sua construção. A extração mineral no RS tem no carvão o seu principal bem mineral, respondendo por 88% dos recursos de carvão do Brasil, para uso na geração termoelétrica e metalúrgico [@RioGrandedoSul-SEPLAN2013a]. Destaca-se também a argila que ocorre junto as jazidas de carvão na região sudoeste para fabricação de cerâmica e as rochas ornamentais (granitos e mármores), cuja produção concentra-se no centro-sul do Estado, especialmente para extração de areia, saibro, argila e carvão para construção civil, indústria e geração de energia.

## Degradação e conservação de ambientes aquáticos {-#Degradação-e-conservação-de-ambientes-aquáticos}

Os ambientes aquáticos são especialmente impactados pelas alterações na cobertura do solo em decorrência da concentração desproporcional da ocupação humana nas proximidades dos recursos hídricos, onde as zonas ripárias são extensamente modificadas mesmo em biomas espaçadamente ocupados [@Postel1996; @Sala2000a]. Os rios são partes funcionais da paisagem porque promovem conectividade pelas matas ripárias, onde ocorrem trocas de materiais, de organismos, de energia e recebem tudo que é escoado na área de captação da bacia [@Wiens2002]. Em comparação com os ambientes terrestres, os aquáticos estão menos disponíveis em área, correspondendo a apenas 0,8% da superfície do planeta [@Dudgeon2006a]. Assim, seu uso disseminado torna mais crítico o fato de as espécies aquáticas apresentarem uma taxa de extinção maior do que as espécies terrestres [@Ricciardi1999a; @Sala2000a; @Jenkins2003; @Vie2009]. Os riachos, cursos d’água de pequeno a médio porte, por sua vez, são ambientes de importantes por comporem grande parte da rede hidrográfica, por sua alta produtividade e heterogeneidade de ambientes, promovendo diversidade de habitats em comparação com rios maiores, além de servirem como habitat para espécies de peixes locais e migratórias. Os rios que recebem a drenagem de riachos cujas bacias são proporcionalmente mais alteradas pelo uso antrópico sofrem maiores influências pelo efeito cumulativo, devido ao fluxo unidirecional das redes hidrográficas [@Allan2004a]. Essas influências podem afetar a qualidade da água e do sedimento e a estabilização dos canais existentes, podendo exercer efeito positivo quando em baixas concentrações. Não por acaso, os processos ecológicos relacionados às espécies de peixes continentais têm em sua conservação um considerável desafio, devido à ação e interação de diferentes fatores de estresse que promovem respostas complexas via caminhos distintos. 

@Dala-Corte2016, ao investigar os mecanismos pelos quais a ictiofauna sofre influência do uso da terra nos campos do sul do Brasil, mostraram diferentes caminhos pelos quais a conversão de paisagem campestre em paisagem agrícola pode causar alterações nas comunidades de peixes. Os efeitos da agricultura foram maiores sobre a diversidade funcional, que, diminui com o incremento da degradação ripária e seus efeitos sobre o aporte de sedimentos ao fundo dos riachos. Por outro lado, os autores observaram um aumento na riqueza taxonômica de espécies, vinculado às modificações no ambiente terrestre em diferentes escalas espaciais. A efetividade das ações de conservação depende, portanto, de mudanças de atitude em relação a biodiversidade aquática, além da aceitação da bacia hidrográfica como unidade espacial de planejamento, especialmente em relação as demandas conflitantes como conservação das espécies, integridade do ecossistema e fornecimento de bens e serviços para as populações humanas [@Dudgeon2006a]. 

Os riachos localizados no Pampa são os locais em cujas margens está situada grande parte da vegetação florestal existente nessa região, mas encontram-se em uma situação vulnerável devido as grandes transformações regionais da paisagem [@Overbeck2007a; @Cordeiro2009a]. A conversão da cobertura vegetal para outros usos, incluindo ou não mudança na configuração das margens de rios e riachos - perda da vegetação e erosão -, afetam diretamente os sistemas aquáticos e a ictiofauna [@Falcone2010]. Portanto, para fundamentar estratégias de conservação da habitats e biota aquática no Pampa, é preciso identificar elementos e padrões que auxiliem no planejamento e na tomada de decisão para a conservação. 

Este trabalho tem por objetivo caracterizar o grau de pressão antrópica sobre bacias hidrográficas de riachos no Pampa sul-brasileiro e avaliar a relação entre a pressão antrópica nessas bacias e características da ictiofauna. Para isso, realizamos primeiramente um diagnóstico de pressão ambiental em 3359 bacias de 3^a^ ordem no bioma Pampa, destacando aquelas com potencial como referência para conservação devido ao baixo grau de pressão. Os resultados deste diagnóstico foram utilizados para testar a existência de relação entre pressão ambiental com as características da ictiofauna: composição e riquezas taxonômica e funcional; e proporção de espécies raras e comuns. Para isso, desenvolvemos um índice global de pressão ambiental baseado em seis indicadores antrópicos com diferentes combinações de pesos visando testar diferentes potencialidades do efeito de cada um na ictiofauna. Esta abordagem permite testar se as classificações baseadas no estado de alteração das bacias estão relacionadas com a ictiofauna.