## Considerações finais {-}

Nossos resultados mostraram que considerar a pressão no bioma Pampa como um todo mascara possíveis variações entre subunidades regionais que podem estar mais pressionadas do que outras. A proporção de bacias hidrográficas com grau de pressão intermediário a alto é mais elevada dentro de algumas fisionomias campestres do que considerando todas as bacias do bioma Pampa somadas, e a existência de relação entre fator de pressão com a ictiofauna depende da variável resposta escolhida. Mapeamentos regionais geralmente não seguem uma especificidade geográfica e de precisão de detalhe que deve ser assumida em estudos focados na conservação da biodiversidade, especialmente em estudos envolvendo ambientes aquáticos, tradicionalmente negligenciados nas políticas de gerenciamento que abordam muito mais as causas e consequências no ambiente terrestre. A multiplicidade de fontes de informação por iniciativas nacionais implica em diferenças no método de geração dos mapeamentos e contribuem para a incerteza dos resultados. Portanto, observar e considerar tais incertezas durante a execução dos estudos é extremamente importante, porque uma das formas de lidar com essa dificuldade ao relacionar informações originadas de formas diferentes, aumentando o realismo da avaliação, é representar todos os indicadores possíveis do conjunto de ameaças presentes nos habitats aquáticos. Iniciativas estaduais com objetivos mais específicos e focados na necessidade e no planejamento regional poderiam ser fomentadas, utilizando proxies quando a informação direta não estiver disponível, porém em nosso estudo mostramos que nem sempre as relações com características ecológicas são simples ou diretas. Mesmo informações adquiridas na fonte primária (como o efetivo de gado, neste trabalho), são obtidas com unidade espacial pouco útil para fins de gerenciamento de bacias. 
