---
title: 'Assessing and supporting working memory in children: the role of attention and the environment'  
subtitle: ''  
author: 
- 'Bruna Arbo Meneses'
description: 
- 'Dissertação de Mestrado apresentada ao Programa de Pós-Graduação em Ecologia, do Instituto de Biociências da Universidade Federal do Rio Grande do Sul, como parte dos requisitos para obtenção do título de Mestre em Ecologia.'
- 'Prof. Dr. Demetrio Luis Guadagnin'
- 'Prof. Dra. Fernanda Thiesen Brum'
- 'Prof. Dr. Uwe H. Schulz'
- 'Orientador: Prof. Dr. Fernando Gertum Becker'
- 'Comissão Examinadora:'
date: 'Porto Alegre, outubro de 2016'
geometry: "left=2.5cm, right=2.5cm, top=2.5cm, bottom=2.5cm"
fontsize: 12pt
linestretch: 1.5
output:
  bookdown::pdf_book:
    fig_caption: yes
    toc: yes
    number_sections: false
    includes:
      in_header: preamble.tex
  bookdown::word_document2:
    fig_caption: true
    toc: yes
    number_sections: false
  html_document:
    df_print: paged
    toc: yes
bibliography: C:/Users/Bruna/Documents/BibTex/dissertacao_final.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::read_chunk("figuras.R")
knitr::read_chunk("tabelas.R")
```

<!-- capa -->


<!-- segunda pagina -->


<!-- terceira pagina -->


<!-- agradecimentos -->


<!-- resumo -->
```{r child = "0-resumo.Rmd"}
```

<!-- abstract -->
```{r child = "0-abstract.Rmd"}
```

<!-- sumario, lista de figuras, lista de taberlas -->


<!-- lista de figuras -->


<!-- introducao -->
```{r child = "1-introducao.Rmd"}
```

<!-- métodos -->
```{r child = "2-metodos.Rmd"}
```

<!-- resultados-->
```{r child = "3-resultados.Rmd"}
```

<!-- discussão
```{r child = "4-discussao.Rmd"}
```

<!-- consideracoes finais
```{r child = "5-consfinais.Rmd"}
```

<!-- referencias
# ```{r child = "99-refs.Rmd"}
# ```

<!-- Apendices
# ```{r child = "999-apendices.Rmd"}
# ```