%% abtex2-modelo-trabalho-academico.tex, v-1.9.7 laurocesar
%% Copyright 2012-2018 by abnTeX2 group at http://www.abntex.net.br/ 
%%
%% This work may be distributed and/or modified under the
%% conditions of the LaTeX Project Public License, either version 1.3
%% of this license or (at your option) any later version.
%% The latest version of this license is in
%%   http://www.latex-project.org/lppl.txt
%% and version 1.3 or later is part of all distributions of LaTeX
%% version 2005/12/01 or later.
%%
%% This work has the LPPL maintenance status `maintained'.
%% 
%% The Current Maintainer of this work is the abnTeX2 team, led
%% by Lauro César Araujo. Further information are available on 
%% http://www.abntex.net.br/
%%
%% This work consists of the files abntex2-modelo-trabalho-academico.tex,
%% abntex2-modelo-include-comandos and abntex2-modelo-references.bib
%%

% ------------------------------------------------------------------------
% ------------------------------------------------------------------------
% abnTeX2: Modelo de Trabalho Academico (tese de doutorado, dissertacao de
% mestrado e trabalhos monograficos em geral) em conformidade com 
% ABNT NBR 14724:2011: Informacao e documentacao - Trabalhos academicos -
% Apresentacao
% ------------------------------------------------------------------------
% ------------------------------------------------------------------------

\documentclass[
	% -- opções da classe memoir --
	12pt,				% tamanho da fonte
	openright,			% capítulos começam em pág ímpar (insere página vazia caso preciso)
	oneside,			% para impressão em recto e verso. Oposto a oneside
	a4paper,			% tamanho do papel. 
	% -- opções da classe abntex2 --
	%chapter=TITLE,		% títulos de capítulos convertidos em letras maiúsculas
	%section=TITLE,		% títulos de seções convertidos em letras maiúsculas
	%subsection=TITLE,	% títulos de subseções convertidos em letras maiúsculas
	%subsubsection=TITLE,% títulos de subsubseções convertidos em letras maiúsculas
	% -- opções do pacote babel --
	english,			% idioma adicional para hifenização
	french,				% idioma adicional para hifenização
	spanish,			% idioma adicional para hifenização
	brazil				% o último idioma é o principal do documento
	]{abntex2}

% ---
% Pacotes básicos 
% ---
\usepackage{lmodern}			% Usa a fonte Latin Modern			
\usepackage[T1]{fontenc}		% Selecao de codigos de fonte.
\usepackage[utf8]{inputenc}		% Codificacao do documento (conversão automática dos acentos)
\usepackage{indentfirst}		% Indenta o primeiro parágrafo de cada seção.
\usepackage{color}				% Controle das cores
\usepackage{graphicx}			% Inclusão de gráficos
\usepackage{microtype} 			% para melhorias de justificação
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{mathtools}
\usepackage[left=2.5cm, top=2.5cm, bottom=2.5cm, right=2.5cm]{geometry}
\usepackage{alltt}




% ---
		
% ---
% Pacotes adicionais, usados apenas no âmbito do Modelo Canônico do abnteX2
% ---
\usepackage{lipsum}				% para geração de dummy text
% ---

% ---
% Pacotes de citações
% ---
\usepackage[brazilian,hyperpageref]{backref}	 % Paginas com as citações na bibl
\usepackage[alf]{abntex2cite}	% Citações padrão ABNT

% --- 
% CONFIGURAÇÕES DE PACOTES
% --- 

% ---
% Configurações do pacote backref
% Usado sem a opção hyperpageref de backref
\renewcommand{\backrefpagesname}{Citado na(s) página(s):~}
% Texto padrão antes do número das páginas
\renewcommand{\backref}{}
% Define os textos da citação
\renewcommand*{\backrefalt}[4]{
	\ifcase #1 %
		Nenhuma citação no texto.%
	\or
		Citado na página #2.%
	\else
		Citado #1 vezes nas páginas #2.%
	\fi}%
% ---

% ---
% Configurações do apendice
% ---
\newcommand{\beginsupplement}{
  \setcounter{table}{0}  
  \renewcommand{\thetable}{A\arabic{table}} 
  \setcounter{figure}{0} 
  \renewcommand{\thefigure}{A\arabic{figure}}
}


% ---
% Informações de dados para CAPA e FOLHA DE ROSTO
% ---
\titulo{Pressão ambiental em bacias hidrográficas do Pampa e sua relação com ictiofauna}
\autor{Bruna Arbo Meneses}
\data{Porto Alegre, outubro de 2016}
\orientador{Fernando Gertum Becker}
\instituicao{%
  UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL
  \par
  INSTITUTO DE BIOCIÊNCIAS
  \par
  PROGRAMA DE PÓS-GRADUAÇÃO EM ECOLOGIA}
\tipotrabalho{Dissertação de Mestrado}
% O preambulo deve conter o tipo do trabalho, o objetivo, 
% o nome da instituição e a área de concentração 
\preambulo{Dissertação de Mestrado apresentada ao Programa de Pós-Graduação em Ecologia, do Instituto de Biociências da Universidade Federal do Rio Grande do Sul, como parte dos requisitos para obtenção do título de Mestre em Ecologia.}
% ---


% ---
% Configurações de aparência do PDF final

% alterando o aspecto da cor azul
\definecolor{blue}{RGB}{41,5,195}

% informações do PDF
\makeatletter
\hypersetup{
     	%pagebackref=true,
		pdftitle={\@title}, 
		pdfauthor={\@author},
    	pdfsubject={\imprimirpreambulo},
	    pdfcreator={LaTeX with abnTeX2},
		pdfkeywords={abnt}{latex}{abntex}{abntex2}{trabalho acadêmico}, 
		colorlinks=true,       		% false: boxed links; true: colored links
    	linkcolor=black,          	% color of internal links
    	citecolor=black,        		% color of links to bibliography
    	filecolor=magenta,      		% color of file links
		urlcolor=black,
		bookmarksdepth=4
}
\makeatother
% --- 

% ---
% Posiciona figuras e tabelas no topo da página quando adicionadas sozinhas
% em um página em branco. Ver https://github.com/abntex/abntex2/issues/170
\makeatletter
\setlength{\@fptop}{5pt} % Set distance from top of page to first float
\makeatother
% ---

% ---
% Possibilita criação de Quadros e Lista de quadros.
% Ver https://github.com/abntex/abntex2/issues/176
%
% \newcommand{\quadroname}{Quadro}
% \newcommand{\listofquadrosname}{Lista de quadros}
% 
% \newfloat[chapter]{quadro}{loq}{\quadroname}
% \newlistof{listofquadros}{loq}{\listofquadrosname}
% \newlistentry{quadro}{loq}{0}
% 
% % configurações para atender às regras da ABNT
% \setfloatadjustment{quadro}{\centering}
% \counterwithout{quadro}{chapter}
% \renewcommand{\cftquadroname}{\quadroname\space} 
% \renewcommand*{\cftquadroaftersnum}{\hfill--\hfill}
% 
% \setfloatlocations{quadro}{hbtp} % Ver https://github.com/abntex/abntex2/issues/176
% % ---

% --- 
% Espaçamentos entre linhas e parágrafos 
% --- 

% O tamanho do parágrafo é dado por:
\setlength{\parindent}{1.3cm}

% Controle do espaçamento entre um parágrafo e outro:
\setlength{\parskip}{0.2cm}  % tente também \onelineskip \parskip{0.2cm}

%Line spacing
\renewcommand{\baselinestretch}{1.6} %Value 	Line spacing: 1.0 	single spacing, 1.3 	one-and-a-half spacing, 1.6 	double spacing.

% ---
% compila o indice
% ---
%\makeindex
% ---

%\usepackage{geometry} %já tem lá em cima
\usepackage{kantlipsum}
\usepackage{fancyhdr}
\fancyhf{} % clear all header and footers
\renewcommand{\headrulewidth}{0pt} % remove the header rule
\fancyfoot[RE,RO]{\thepage} % Left side on Even pages; Right side on Odd pages
\pagestyle{fancy}
\fancypagestyle{plain}{%
  \fancyhf{}%
  \renewcommand{\headrulewidth}{0pt}%
  \fancyhf[lef,rof]{\thepage}%
}

% ----
% Início do documento
% ----
\begin{document}
%\pagestyle{plain}
\pagestyle{fancy}
\fancypagestyle{plain}{%
  \fancyhf{}%
  \renewcommand{\headrulewidth}{0pt}%
  \fancyhf[lef,rof]{\thepage}%
}
% Seleciona o idioma do documento (conforme pacotes do babel)
%\selectlanguage{english}
\selectlanguage{brazil}

% Retira espaço extra obsoleto entre as frases.
\frenchspacing 

% ----------------------------------------------------------
% ELEMENTOS PRÉ-TEXTUAIS
% ----------------------------------------------------------
% \pretextual

% ---
% Capa
% ---
%\imprimircapa
% ---

% ---
% Folha de rosto
% (o * indica que haverá a ficha bibliográfica)
% ---
%\imprimirfolhaderosto*
% ---

% ---
% Inserir a ficha bibliografica
% ---

% Isto é um exemplo de Ficha Catalográfica, ou ``Dados internacionais de
% catalogação-na-publicação''. Você pode utilizar este modelo como referência. 
% Porém, provavelmente a biblioteca da sua universidade lhe fornecerá um PDF
% com a ficha catalográfica definitiva após a defesa do trabalho. Quando estiver
% com o documento, salve-o como PDF no diretório do seu projeto e substitua todo
% o conteúdo de implementação deste arquivo pelo comando abaixo:
%
% \begin{fichacatalografica}
%     \includepdf{fig_ficha_catalografica.pdf}
% \end{fichacatalografica}

% \begin{fichacatalografica}
% 	\sffamily
% 	\vspace*{\fill}					% Posição vertical
% 	\begin{center}					% Minipage Centralizado
% 	\fbox{\begin{minipage}[c][8cm]{13.5cm}		% Largura
% 	\small
% 	\imprimirautor
% 	%Sobrenome, Nome do autor
% 	
% 	\hspace{0.5cm} \imprimirtitulo  / \imprimirautor. --
% 	\imprimirlocal, \imprimirdata-
% 	
% 	\hspace{0.5cm} \thelastpage p. : il. (algumas color.) ; 30 cm.\\
% 	m
% 	\hspace{0.5cm} \imprimirorientadorRotulo~\imprimirorientador\\
% 	
% 	\hspace{0.5cm}
% 	\parbox[t]{\textwidth}{\imprimirtipotrabalho~--~\imprimirinstituicao,
% 	\imprimirdata.}\\
% 	
% 	\hspace{0.5cm}
% 		1. Palavra-chave1.
% 		2. Palavra-chave2.
% 		2. Palavra-chave3.
% 		I. Orientador.
% 		II. Universidade xxx.
% 		III. Faculdade de xxx.
% 		IV. Título 			
% 	\end{minipage}}
% 	\end{center}
% \end{fichacatalografica}
% ---

% ---
% % Inserir errata
% % ---
% \begin{errata}
% Elemento opcional da \citeonline[4.2.1.2]{NBR14724:2011}. Exemplo:
% 
% \vspace{\onelineskip}
% 
% FERRIGNO, C. R. A. \textbf{Tratamento de neoplasias ósseas apendiculares com
% reimplantação de enxerto ósseo autólogo autoclavado associado ao plasma
% rico em plaquetas}: estudo crítico na cirurgia de preservação de membro em
% cães. 2011. 128 f. Tese (Livre-Docência) - Faculdade de Medicina Veterinária e
% Zootecnia, Universidade de São Paulo, São Paulo, 2011.
% 
% \begin{table}[htb]
% \center
% \footnotesize
% \begin{tabular}{|p{1.4cm}|p{1cm}|p{3cm}|p{3cm}|}
%   \hline
%    \textbf{Folha} & \textbf{Linha}  & \textbf{Onde se lê}  & \textbf{Leia-se}  \\
%     \hline
%     1 & 10 & auto-conclavo & autoconclavo\\
%    \hline
% \end{tabular}
% \end{table}
% 
% \end{errata}
% % ---

% % ---
% % Inserir folha de aprovação
% % ---
% 
% % Isto é um exemplo de Folha de aprovação, elemento obrigatório da NBR
% % 14724/2011 (seção 4.2.1.3). Você pode utilizar este modelo até a aprovação
% % do trabalho. Após isso, substitua todo o conteúdo deste arquivo por uma
% % imagem da página assinada pela banca com o comando abaixo:
% %
% % \begin{folhadeaprovacao}
% % \includepdf{folhadeaprovacao_final.pdf}
% % \end{folhadeaprovacao}
% %
% \begin{folhadeaprovacao}
% 
%   \begin{center}
%     {\ABNTEXchapterfont\large\imprimirautor}
% 
%     \vspace*{\fill}\vspace*{\fill}
%     \begin{center}
%       \ABNTEXchapterfont\bfseries\Large\imprimirtitulo
%     \end{center}
%     \vspace*{\fill}
%     
%     \hspace{.45\textwidth}
%     \begin{minipage}{.5\textwidth}
%         \imprimirpreambulo
%     \end{minipage}%
%     \vspace*{\fill}
%    \end{center}
%         
%    Trabalho aprovado. \imprimirlocal, 24 de novembro de 2012:
% 
%    \assinatura{\textbf{\imprimirorientador} \\ Orientador} 
%    \assinatura{\textbf{Professor} \\ Convidado 1}
%    \assinatura{\textbf{Professor} \\ Convidado 2}
%    %\assinatura{\textbf{Professor} \\ Convidado 3}
%    %\assinatura{\textbf{Professor} \\ Convidado 4}
%       
%    \begin{center}
%     \vspace*{0.5cm}
%     {\large\imprimirlocal}
%     \par
%     {\large\imprimirdata}
%     \vspace*{1cm}
%   \end{center}
%   
% \end{folhadeaprovacao}
% % ---

% % ---
% % Dedicatória
% % ---
% \begin{dedicatoria}
%    \vspace*{\fill}
%    \centering
%    \noindent
%    \textit{ Este trabalho é dedicado às crianças adultas que,\\
%    quando pequenas, sonharam em se tornar cientistas.} \vspace*{\fill}
% \end{dedicatoria}
% % ---

% ---
% Agradecimentos
% ---
\pagestyle{empty} %get rid of header/footer for toc page

\begin{agradecimentos}
Durante o período do mestrado, contei com uma grande rede de apoio agindo direta e indiretamente no desenvolvimento desta dissertação. Pessoas e instituições que, ao fazerem parte dessa incrível experiência de compartilhamento que é a vida, contribuíram com um pedacinho de si na construção da profissional que me torno a cada novo encontro neste caminho. Gostaria de agradecer especialmente:

-- ao Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq) pela bolsa de mestrado; e ao Programa de Pesquisa em Biodiversidade (PPBio);

-- Bioma Campos Sulinos (proc. 457503/2012-2.) do CNPq que financiou grande parte desta pesquisa;

-- ao meu orientador, Fernando Gertum Becker, pela amizade e incentivo, por compartilhar seus conhecimentos, pela desorientação eventual - no melhor sentido possível -, por me lembrar sempre como são empolgantes os meandros da ecologia e da pesquisa;

-- a todos os amigos e colegas do Laboratório de Ecologia de Paisagens, pelas discussões, chimarrões da alegria, abraços calmantes, guloseimas pilhantes e insights motivadores durante o trabalho;

-- a Caroline Hartmann, ao Fernando Becker, a Taís Ramos Guimarães e, principalmente, ao Renato Bolson Dala Corte pelos ensinamentos de campo, de direção off-road e de mecânica básica; ao Renato também pela paciência, parceria e ajuda estatístico-terapêutica;

-- Mateus Camana, Matheus Dalmolin, Lucas de Fries, Luciana Podgaiski, Vinicius Bastazini, Vinicius Lampert, Miguel Santos, Karine Bonato, Rafael A. Silveira, Angelo Meneses, Luiz Henrique e Bento Collares por terem embarcado nessa pra ajudar nos campos; e a todos os proprietários que receberam as equipes de peixes PPBio durante os trabalhos de campo. A disponibilidade de vocês foi fundamental;

-- aos amigos Larissa Gonçalves, Ismael Brack, Fernanda Zimmermann, Andreas Kindel, Igor Coelho, Julia Beduschi, Juan Rodriguez e Paula Pinheiro (NERF, muito obrigada pelos abrigos!!), mais Luis Fernando Marin, Michelle Abadie, Vinícius Bastazini, Anita Macedo, Isadora Neumann e Danielle Calegari por, pra dizer o mínimo, ajudarem a manter meu ambiente interno estável\ldots{} que alegria é ter vocês na vida, sabe?

-- ao Juliano Ferrer dos Santos, do Laboratório de Ictiologia da UFRGS, por ajudar na identificação das espécies de peixes;

-- ao Prof.~Dr.~Luis R. Malabarba, por coordenar do projeto associado Peixes -- PPBio pelo apoio operacional;

-- ao Prof.~Dr.~Valério de Patta Pillar, por coordenar o PPBio Campos Sulinos e ao Eduardo Velez, pela disponibilidade e apoio operacional;

-- ao Programa de Pós-Graduação em Ecologia da UFRGS por todo o suporte, pelas disciplinas e resolução das questões administrativas.

-- aos membros da banca avaliadora, Prof.~Dr.~Demetrio Luis Guadagnin, Prof.~Dra. Fernanda Thiesen Brum e Prof.~Dr.~Uwe H. Schulz, por terem aceitado avaliar a minha dissertação e pelas contribuições que serão tão bem vindas.

-- e por último, mas mais importante, à minha mãe, Beth, ao meu pai, Angelo e à ermãzita Renata, simplesmente por existirem, por estarem junto, por ficarem do meu lado mesmo quando discordaram. Pelo apoio logístico, gastronômico, emocional e financeiro sempre que foi preciso (e olha que foi preciso muito!). Sem vocês, tudo teria sido incrivelmente mais difícil. Amo vocês demais da conta.
\end{agradecimentos}
% ---

% ---
% Epígrafe
% ---
\begin{epigrafe}
    \vspace*{\fill}
	\begin{flushright}
		{\emph{Human beings are stewards of nature, whether we like it or not.}\\
Sanderson et al.~(2002), Trends in Ecology \& Evolution 23.}
	\end{flushright}
\end{epigrafe}
% ---

% ---
% RESUMOS
% ---

% resumo em português
\setlength{\absparsep}{18pt} % ajusta o espaçamento dos parágrafos do resumo
\begin{resumo}
 Classificações de bacias hidrográficas baseadas em indicadores de pressão ambiental permitem caracterizar gradientes de degradação potencial que podem estar relacionados à conservação da biota. Por exemplo, é plausível assumir que existe uma relação negativa entre diversidade de espécies e pressão ambiental como fundamento para uso de mapas de pressão na priorização de bacias para conservação, mas esse é um pressuposto que deve ser validado, sob pena de o objetivo de conservação (como diversidade) não ser efetivamente afetado por ações de conservação baseadas nos fatores de pressão. Neste trabalho, apresentamos um diagnóstico de pressão ambiental em 3359 bacias de 3\textsuperscript{a} ordem no bioma Pampa e utilizamos estes resultados para testar a existência de relação com características da ictiofauna. Definimos o grau de pressão sobre as bacias como um índice global composto por seis indicadores e realizamos projeções considerando cinco diferentes configurações de pesos para esses indicadores. Consideramos como bacias de referência aquelas que atenderam a uma das seguintes condições: 1) apresentarem valor zero para todos os fatores de pressão, ou 2) estarem entre as 10\% menos pressionadas em cada subunidade regional. O dados de ictiofauna foram obtidos em 52 bacias hidrográficas de 3\textsuperscript{a} ordem, sendo cada bacia representada com amostragem por pesca elétrica em 150 m de riacho. Foram ainda discriminadas 13 subunidades regionais definidas pela combinação de ecorregiões aquáticas e fisionomias campestres. Todas as bacias mostraram a presença de pelo menos um indicador de pressão, sendo que bacias de referência foram identificadas somente em duas subunidades regionais. Há uma proporção elevada de bacias (acima de 50\%) com níveis intermediários a altos de pressão no bioma Pampa, sendo tais proporções variáveis entre subunidades fisionômicas de campo e subunidades ecorregionais aquáticas. Ao buscar relações entre os fatores de pressão e características da ictiofauna, verificamos que a composição taxonômica está relacionada com agricultura e espelhos d'água (representados principalmente por açudes). Verificamos ainda que a riqueza taxonômica está relacionada negativamente com agricultura. Riqueza funcional, composição funcional e porcentagens de espécies raras e comuns não apresentaram relação com o gradiente de pressão. Os resultados mostram que apenas parte das características ecológicas da ictiofauna possui relação direta com grau de pressão ambiental em bacias hidrográficas, indicando que a validade do uso de fatores de pressão como proxies depende de quais características de ictiofauna são consideradas. Portanto, para que os resultados de estratégias regionais de conservação de ictiofauna sejam eficientes, o mapeamento de fatores de pressão deve ser baseado na definição adequada de alvos e complementado por testes sobre sua relação com os alvos de conservação.
 
 \vspace{\onelineskip}
 
 \noindent 
 \textbf{Palavras-chave}: Planejamento sistemático de conservação, campos sulinos, biodiversidade aquática, análise multicritério, peixes
\end{resumo}

% resumo em inglês
\begin{resumo}[Abstract]
 \begin{otherlanguage*}{english}
   Watershed classification using spatial representations of biodiversity threatening factors are useful as proxies of disturbance gradients. However, this is an assumption that should be tested in order to effectively link conservation objectives to biodiversity outcomes. In this study, we test whether stream fish community attributes are related to environmental pressure in small watersheds of the Brazilian Pampa grassland biome. Firstly, we estimated and mapped environmental pressure in 3359 third-order watersheds, then we tested whether environmental pressure predicted fish community attributes in 150-m stream segments from 52 watersheds representing the gradient of environmental pressure. Environmental pressure was defined by an index based on six indicators (cropland, mining, urbanization, road density, dams and cattle density). We defined reference watersheds as those where all the indicators were equal to zero or which were ranked among the 10\% less disturbed in each subregional Pampa unit (aquatic ecorregions and regional grassland types). All watersheds had the influence of at least one disturbance factor, and reference watersheds were indentified in only one subregional unit. An elevated fraction of the watersheds (over 50\%) showed intermediate to high pressure. Redundancy Analysis (RDA) indicated that that taxonomic composition was related to cropland area and dams. GLM results indicated that taxonomic richness is negatively related to cropland area. Functional richness and composition, and proportion of rare and common species were not related to the environmental pressure gradient. Our results show that response of fish communities to environmental pressure gradient may vary from positive, to negative or no response, depending on the selected attribute. Concerning the use in scientifically defensible conservation strategies, mapping pressure indicators could be enhanced by testing their relationship with conservation biodiversity outcomes.

   \vspace{\onelineskip}
 
   \noindent 
   \textbf{Keywords}: systematic conservation planning, campos sulinos, freshwater diversity, multicriteria analysis, fishes.
 \end{otherlanguage*}
\end{resumo}

% resumo em francês 
% \begin{resumo}[Résumé]
%  \begin{otherlanguage*}{french}
%     Il s'agit d'un résumé en français.
%  
%    \textbf{Mots-clés}: latex. abntex. publication de textes.
%  \end{otherlanguage*}
% \end{resumo}
% 
% % resumo em espanhol
% \begin{resumo}[Resumen]
%  \begin{otherlanguage*}{spanish}
%    Este es el resumen en español.
%   
%    \textbf{Palabras clave}: latex. abntex. publicación de textos.
%  \end{otherlanguage*}
% \end{resumo}
% % ---

% ---
% inserir o sumario
% ---
\pdfbookmark[0]{\contentsname}{toc}
\tableofcontents*
%\cleardoublepage
\newpage
% ---

% % ---
% % inserir lista de quadros
% % ---
% \pdfbookmark[0]{\listofquadrosname}{loq}
% \listofquadros*
% \cleardoublepage
% % ---

% ---
% inserir lista de ilustrações
% ---
\renewcommand{\baselinestretch}{1}
\pdfbookmark[0]{\listfigurename}{lof}
\listoffigures*
%\cleardoublepage
\newpage
% ---

% ---
% inserir lista de tabelas
% ---
\renewcommand{\baselinestretch}{1}
\pdfbookmark[0]{\listtablename}{lot}
\listoftables*
%\cleardoublepage
\newpage

\renewcommand{\baselinestretch}{1.6}
% ---

%% ---
%% inserir lista de abreviaturas e siglas
%% ---
%\begin{siglas}
%  \item[ABNT] Associação Brasileira de Normas Técnicas
%  \item[abnTeX] ABsurdas Normas para TeX
%\end{siglas}
% ---

% ----------------------------------------------------------
% ELEMENTOS TEXTUAIS
% ----------------------------------------------------------
\textual
%\pagestyle{plain}
\pagestyle{fancy}
\fancypagestyle{plain}{%
  \fancyhf{}%
  \renewcommand{\headrulewidth}{0pt}%
  \fancyhf[lef,rof]{\thepage}%
}

\hypertarget{Introduuxe7uxe3o}{%
\section*{Introdução}\label{Introduuxe7uxe3o}}
\addcontentsline{toc}{section}{Introdução}

Os usos antrópicos dos recursos ambientais têm moldado em escala global os padrões espaciais dos ecossistemas, determinando a magnitude da perda de biodiversidade e de serviços ecossistêmicos e tornando raros os locais no planeta que não sofrem algum grau de influência humana (Sanderson et al. \protect\hyperlink{ref-Sanderson2002}{2002}; Vörösmarty et al. \protect\hyperlink{ref-Vorosmarty2010}{2010}). Para a maioria dos ecossistemas, as atividades humanas que se caracterizam como as principais ameaças a curto prazo são a expansão da agricultura e das áreas urbanas (Allan \protect\hyperlink{ref-Allan2004a}{2004}; FAO \protect\hyperlink{ref-FAO2010}{2010}). A expansão da malha rodoviária é também um fator de ameaça, seja pela implantação das rodovias em si, seja pelo acesso que elas proporcionam a locais até então inalterados (Trombulak and Frissell \protect\hyperlink{ref-Trombulak2000}{2000}; Sanderson et al. \protect\hyperlink{ref-Sanderson2002}{2002}; Angermeier, Wheeler, and Rosenberger \protect\hyperlink{ref-Angermeier2004a}{2004}; Laurance and Balmford \protect\hyperlink{ref-Laurance2013}{2013}). No Brasil, a previsão é de que, até 2024, haja um aumento no uso da terra correspondente a 20\% sobre a área média durante os anos de 2012 a 2014, especialmente para cultivos de oleaginosas, cereais, cana e algodão (Vinet and Zhedanov \protect\hyperlink{ref-Vinet2016}{2016}). Podemos esperar, consequentemente, um efeito em cascata no sentido do investimento em infraestrutura e matéria-prima para produção e distribuição desta atividade.

Devido a essa dinâmica em escala regional de expansão da ação humana, a aplicação dos princípios de planejamento sistemático para conservação tem crescido, com o intuito de localizar áreas prioritárias de forma organizada e objetiva, contemplando o maior número de aspectos bióticos e abióticos que definam interesse para conservação, como por exemplo, áreas hipoteticamente intocadas ou pouco degradadas (Margules and Pressey \protect\hyperlink{ref-Margules2000}{2000}; Linke, Turak, and Nel \protect\hyperlink{ref-Linke2011c}{2011}; Lourival et al. \protect\hyperlink{ref-Lourival2011a}{2011}), áreas de biodiversidade elevada ou biogeograficamente representativas, áreas importantes para serviços ecossistêmicos, ou, áreas fortemente pressionadas e que reúnam alguma das características anteriores (Myers et al. \protect\hyperlink{ref-Myers2000}{2000}; Brooks et al. \protect\hyperlink{ref-Brooks2006}{2006}). O planejamento sistemático de conservação tem como característica principal as escolhas claras e explícitas no processo do planejamento tanto no que diz respeito as características dos componentes da biodiversidade a serem usados no processo de planejamento, quanto nos objetivos de conservação, sempre que possível traduzidos em metas quantitativas e operacionais (Pressey et al. \protect\hyperlink{ref-Pressey2007}{2007}). O uso dos sistemas de informação geográfica (SIG) facilita a visualização dessas alterações no espaço permitindo maior eficiência e sistematização nas relações das alterações na cobertura do solo na biodiversidade e suas consequências para o planejamento territorial (Tulloch et al. \protect\hyperlink{ref-Tulloch2015}{2015}). Avaliações em escala espacial ampla, de unidades de paisagem - como bacias hidrográficas - são necessárias para gerenciamento do território, tomada de decisão e manejo da fauna porque é a escala em que os efeitos cumulativos dos impactos ficam evidentes, tornando as causas da degradação ambiental mais facilmente observáveis (O'Neill et al. \protect\hyperlink{ref-ONeill1997}{1997}; Wiens \protect\hyperlink{ref-Wiens2002}{2002}; Stein, Stein, and Nix \protect\hyperlink{ref-Stein2002a}{2002}).

Quando o interesse de conservação está na biodiversidade aquática de água-doce, as unidades espaciais empregadas na análise podem ser rios, riachos ou bacias hidrográficas. Rios e riachos são geralmente afetados por múltiplos distúrbios que se acumulam e interagem no espaço e no tempo, tornando o entendimento da resposta para determinadas ameaças uma tarefa complexa (Allan \protect\hyperlink{ref-Allan2004a}{2004}). É importante ressaltar que estes indicadores de pressão representam uma degradação potencial do ambiente e não da degradação efetiva, a qual é resultado da interação de fatores cujo histórico, intensidade, frequência e efeito variam regionalmente. De posse dessas informações, é possível determinar quais unidades de paisagem recebem maior pressão por atividades antrópicas e assumir que aquelas onde há ausência de pressão ambiental - ou pelo menos aquelas menos pressionadas - sejam tratadas como sítios de referência para comparações dos padrões observados ao longo de gradientes de pressão (Stoddard et al. \protect\hyperlink{ref-Stoddard2006}{2006}). A condição destas unidades pode ser definida como a similaridade do sítio avaliado em relação a um conjunto de sítios menos degradados, levando em consideração características bióticas (conjunto de indicadores, como o número de espécies intolerantes, riqueza e composição de espécies; espécies ameaçadas, etc.) (Stoddard et al. \protect\hyperlink{ref-Stoddard2006}{2006}; Allan et al. \protect\hyperlink{ref-Allan2013}{2013}).

Normalmente assume-se que existe uma relação negativa entre diversidade de espécies e pressão ambiental como fundamento para uso de mapas de pressão na priorização de áreas para conservação e que a proteção de determinado conjunto de características abióticas (mais fáceis de quantificar) consequentemente conservará o conjunto de espécies que ocorram neste local (Stein, Stein, and Nix \protect\hyperlink{ref-Stein2002a}{2002}; Khoury, Higgins, and Weitzell \protect\hyperlink{ref-Khoury2011a}{2011}; Tulloch et al. \protect\hyperlink{ref-Tulloch2015}{2015}).
Entretanto, esse é um pressuposto que deve ser validado para que o objetivo de conservação seja efetivamente alcançado. Alguns trabalhos não consideram dados bióticos na determinação de locais que sirvam como referência para conservação com menor influência antrópica (Sanderson et al. \protect\hyperlink{ref-Sanderson2002}{2002}), e outros consideram os alvos de conservação ao dar pesos aos indicadores relacionados ao efeito potencial que eles tem sobre as espécies (Stein, Stein, and Nix \protect\hyperlink{ref-Stein2002a}{2002}; Heiner et al. \protect\hyperlink{ref-Heiner2011a}{2011}), mas poucos são os que validam esta relação com dados de campo para mostrar que ela verdadeiramente existe (Esselman et al. \protect\hyperlink{ref-Esselman2011b}{2011}; Ligeiro et al. \protect\hyperlink{ref-Ligeiro2013}{2013}). A comparação de dados de campo aumenta a eficiência das ações de conservação ao esclarecer a relação do objetivo de conservação (por exemplo, diversidade) e os fatores de pressão (Tulloch et al. \protect\hyperlink{ref-Tulloch2013}{2013}).

\hypertarget{a-conservacao-de-riachos-nos-campos-do-pampa}{%
\subsection*{A conservação de riachos nos campos do Pampa}\label{a-conservacao-de-riachos-nos-campos-do-pampa}}
\addcontentsline{toc}{subsection}{A conservação de riachos nos campos do Pampa}

Os ambientes campestres são bastante sensíveis às mudanças da cobertura do solo, não importa em que região do planeta estejam localizados (Sala \protect\hyperlink{ref-Sala2000a}{2000}; Andrade et al. \protect\hyperlink{ref-Andrade2015a}{2015}). Embora sejam ricos em número de espécies (Overbeck et al. \protect\hyperlink{ref-Overbeck2005}{2005}, \protect\hyperlink{ref-Overbeck2006}{2006}; Wilson et al. \protect\hyperlink{ref-Wilson2012}{2012}) e ofereçam inúmeros serviços ecossistêmicos, com frequência são ignorados como alvo de conservação. As regiões campestres localizadas na metade sul do Rio Grande do Sul fazem parte do chamado Pampa, bioma de campos que inclui ainda partes do Uruguai e Argentina (Overbeck et al. \protect\hyperlink{ref-Overbeck2007a}{2007}). A proporção de remanescentes de campos é de aproximadamente 50\% em relação a sua área original no Rio Grande do Sul, por conta da acelerada conversão do solo para, principalmente, a agricultura e a silvicultura (Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}) e apenas 0,33\% dos campos estão atualmente protegidos em unidades de proteção integral (Overbeck et al. \protect\hyperlink{ref-Overbeck2007a}{2007}).

Os principais usos presentes no bioma Pampa são pecuária e agricultura, que podem aparecer em associação por rodízio de culturas (Nabinger, Moraes, and Maraschin \protect\hyperlink{ref-Nabinger2000}{2000}). A agricultura apresentou crescimento mais intenso nas últimas décadas, especialmente pelos cultivos de arroz, milho, soja, trigo e silvicultura (IBGE \protect\hyperlink{ref-IBGE2015}{2015}), atividades que contam com incentivo de empresas privadas e do governo, com consequente diminuição das áreas de vegetação nativa (Nabinger, Moraes, and Maraschin \protect\hyperlink{ref-Nabinger2000}{2000}; Overbeck et al. \protect\hyperlink{ref-Overbeck2007a}{2007}; Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}). A construção de açudes para dessedentação animal e para irrigação da plantações é uma consequência dessas atividades econômicas, e representam grave influência na fragmentação da rede hidrográfica (Clavero and Hermoso \protect\hyperlink{ref-Clavero2011}{2011}), uma vez que nem sempre necessitam de licenciamento ambiental prévio para sua construção. A extração mineral no RS tem no carvão o seu principal bem mineral, respondendo por 88\% dos recursos de carvão do Brasil, para uso na geração termoelétrica e metalúrgico (Rio Grande do Sul - SEPLAN \protect\hyperlink{ref-RioGrandedoSul-SEPLAN2013a}{2013}). Destaca-se também a argila que ocorre junto as jazidas de carvão na região sudoeste para fabricação de cerâmica e as rochas ornamentais (granitos e mármores), cuja produção concentra-se no centro-sul do Estado, especialmente para extração de areia, saibro, argila e carvão para construção civil, indústria e geração de energia.

\hypertarget{Degradauxe7uxe3o-e-conservauxe7uxe3o-de-ambientes-aquuxe1ticos}{%
\subsection*{Degradação e conservação de ambientes aquáticos}\label{Degradauxe7uxe3o-e-conservauxe7uxe3o-de-ambientes-aquuxe1ticos}}
\addcontentsline{toc}{subsection}{Degradação e conservação de ambientes aquáticos}

Os ambientes aquáticos são especialmente impactados pelas alterações na cobertura do solo em decorrência da concentração desproporcional da ocupação humana nas proximidades dos recursos hídricos, onde as zonas ripárias são extensamente modificadas mesmo em biomas espaçadamente ocupados (Postel, Daily, and Ehrlich \protect\hyperlink{ref-Postel1996}{1996}; Sala \protect\hyperlink{ref-Sala2000a}{2000}). Os rios são partes funcionais da paisagem porque promovem conectividade pelas matas ripárias, onde ocorrem trocas de materiais, de organismos, de energia e recebem tudo que é escoado na área de captação da bacia (Wiens \protect\hyperlink{ref-Wiens2002}{2002}). Em comparação com os ambientes terrestres, os aquáticos estão menos disponíveis em área, correspondendo a apenas 0,8\% da superfície do planeta (Dudgeon et al. \protect\hyperlink{ref-Dudgeon2006a}{2006}). Assim, seu uso disseminado torna mais crítico o fato de as espécies aquáticas apresentarem uma taxa de extinção maior do que as espécies terrestres (Ricciardi and Rasmussen \protect\hyperlink{ref-Ricciardi1999a}{1999}; Sala \protect\hyperlink{ref-Sala2000a}{2000}; Jenkins \protect\hyperlink{ref-Jenkins2003}{2003}; Vié, Hilton-Taylor, and Stuart \protect\hyperlink{ref-Vie2009}{2009}). Os riachos, cursos d'água de pequeno a médio porte, por sua vez, são ambientes de importantes por comporem grande parte da rede hidrográfica, por sua alta produtividade e heterogeneidade de ambientes, promovendo diversidade de habitats em comparação com rios maiores, além de servirem como habitat para espécies de peixes locais e migratórias. Os rios que recebem a drenagem de riachos cujas bacias são proporcionalmente mais alteradas pelo uso antrópico sofrem maiores influências pelo efeito cumulativo, devido ao fluxo unidirecional das redes hidrográficas (Allan \protect\hyperlink{ref-Allan2004a}{2004}). Essas influências podem afetar a qualidade da água e do sedimento e a estabilização dos canais existentes, podendo exercer efeito positivo quando em baixas concentrações. Não por acaso, os processos ecológicos relacionados às espécies de peixes continentais têm em sua conservação um considerável desafio, devido à ação e interação de diferentes fatores de estresse que promovem respostas complexas via caminhos distintos.

Dala-Corte et al. (\protect\hyperlink{ref-Dala-Corte2016}{2016}), ao investigar os mecanismos pelos quais a ictiofauna sofre influência do uso da terra nos campos do sul do Brasil, mostraram diferentes caminhos pelos quais a conversão de paisagem campestre em paisagem agrícola pode causar alterações nas comunidades de peixes. Os efeitos da agricultura foram maiores sobre a diversidade funcional, que, diminui com o incremento da degradação ripária e seus efeitos sobre o aporte de sedimentos ao fundo dos riachos. Por outro lado, os autores observaram um aumento na riqueza taxonômica de espécies, vinculado às modificações no ambiente terrestre em diferentes escalas espaciais. A efetividade das ações de conservação depende, portanto, de mudanças de atitude em relação a biodiversidade aquática, além da aceitação da bacia hidrográfica como unidade espacial de planejamento, especialmente em relação as demandas conflitantes como conservação das espécies, integridade do ecossistema e fornecimento de bens e serviços para as populações humanas (Dudgeon et al. \protect\hyperlink{ref-Dudgeon2006a}{2006}).

Os riachos localizados no Pampa são os locais em cujas margens está situada grande parte da vegetação florestal existente nessa região, mas encontram-se em uma situação vulnerável devido as grandes transformações regionais da paisagem (Overbeck et al. \protect\hyperlink{ref-Overbeck2007a}{2007}; Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}). A conversão da cobertura vegetal para outros usos, incluindo ou não mudança na configuração das margens de rios e riachos - perda da vegetação e erosão -, afetam diretamente os sistemas aquáticos e a ictiofauna (Falcone, Carlisle, and Weber \protect\hyperlink{ref-Falcone2010}{2010}). Portanto, para fundamentar estratégias de conservação da habitats e biota aquática no Pampa, é preciso identificar elementos e padrões que auxiliem no planejamento e na tomada de decisão para a conservação.

Este trabalho tem por objetivo caracterizar o grau de pressão antrópica sobre bacias hidrográficas de riachos no Pampa sul-brasileiro e avaliar a relação entre a pressão antrópica nessas bacias e características da ictiofauna. Para isso, realizamos primeiramente um diagnóstico de pressão ambiental em 3359 bacias de 3\textsuperscript{a} ordem no bioma Pampa, destacando aquelas com potencial como referência para conservação devido ao baixo grau de pressão. Os resultados deste diagnóstico foram utilizados para testar a existência de relação entre pressão ambiental com as características da ictiofauna: composição e riquezas taxonômica e funcional; e proporção de espécies raras e comuns. Para isso, desenvolvemos um índice global de pressão ambiental baseado em seis indicadores antrópicos com diferentes combinações de pesos visando testar diferentes potencialidades do efeito de cada um na ictiofauna. Esta abordagem permite testar se as classificações baseadas no estado de alteração das bacias estão relacionadas com a ictiofauna.

\hypertarget{Muxe9todos}{%
\section*{Métodos}\label{Muxe9todos}}
\addcontentsline{toc}{section}{Métodos}

Neste trabalho, realizamos um diagnóstico do estado de pressão ambiental nas bacias hidrográficas de riachos de 3\textsuperscript{a} ordem situadas no bioma Pampa (IBGE \protect\hyperlink{ref-IBGE2004}{2004}) com base em seis indicadores de pressão ambiental: agricultura, área urbana, mineração, espelhos d'água maiores do que 20 ha, densidade viária e densidade de gado (para detalhamento dos indicadores, ver mais abaixo). Posteriormente, investigamos a relação entre o gradiente de pressão ambiental das bacias e as riquezas e composições taxonômica e funcional de peixes, além da proporção de espécies raras e de espécies comuns. As bacias de 3\textsuperscript{a} ordem foram derivadas de um modelo digital de elevação hidrologicamente consistido (MDT-HC), para as quais foram quantificadas a presença de cada indicador de pressão ambiental. Um índice global foi elaborado para quantificar a pressão ambiental global em cada bacia através de métricas derivadas em sistema de informação geográfica (SIG).

\hypertarget{area-de-estudo-e-estrutura-espacial}{%
\subsection*{Área de estudo e estrutura espacial}\label{area-de-estudo-e-estrutura-espacial}}
\addcontentsline{toc}{subsection}{Área de estudo e estrutura espacial}

As análises envolveram a área do bioma Pampa (IBGE \protect\hyperlink{ref-IBGE2004}{2004}), que se estende por 176.476 km\textsuperscript{2} no estado do Rio Grande do Sul, sul do Brasil (Figura \ref{fig:areaestudo}).
A cobertura vegetal desta região, zona de transição entre os climas temperado e tropical, corresponde a um mosaico de campos nativos, arbustos e manchas florestais que, desconsiderando os limites políticos, estendem-se pelo Uruguai e parte da Argentina (Overbeck et al. \protect\hyperlink{ref-Overbeck2007a}{2007}). As áreas campestres e florestais no Rio Grande do Sul sem qualquer intervenção antrópica são muito pequenas, porque mesmo as áreas sob algum tipo de proteção, como as unidades de conservação, apresentam algum tipo de pressão antrópica, especialmente por pecuária (Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}). O Rio Grande do Sul possui o 6º efetivo bovino no país, com números estáveis nas últimas décadas (1980-2014), embora este rebanho esteja em franco crescimento no Brasil. Suínos (3º maior efetivo no Brasil) e ovinos (estado com maior número de cabeças) são os outros rebanhos mais comuns (IBGE \protect\hyperlink{ref-IBGE2015}{2015}).

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/01_AreaDeEstudoFisionmiascampestres_meiaA4_v2} 

}

\caption[Área de estudo abordada no diagnóstico de pressão ambiental no bioma Pampa.]{Área de estudo abordada no diagnóstico de pressão ambiental no bioma Pampa. Fisionomias campestres: CArb = Campo Arbustivo; CAre = Campo com Areais; CBDB = Campo com Barba-de-Bode; CEsp = Campo com Espinilho; CSR = Campo com Solos Rasos; CGra = Campo Graminoso; CMAC = Campo Misto com Andropogôneas e Compostas; CMCO = Campo Misto do Cristalino Oriental; FE = Floresta Estacional.}\label{fig:areaestudo}
\end{figure}

A expansão da agricultura, que cobre aproximadamente 40\% da área do bioma Pampa, representada especialmente pelas lavouras temporárias de grãos como soja, trigo e arroz, compreende uma das principais ameaças à conservação dos campos pelas intensas conversões no uso do solo que acarretam (Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}); (IBGE \protect\hyperlink{ref-IBGE2015}{2015})). A silvicultura também constitui atividade em expansão no Rio Grande do Sul, com a plantação de eucalipto, acácia-negra e pinus (Guadagnin et al. \protect\hyperlink{ref-Guadagnin2010}{2010}) que servem de matéria-prima para indústrias de papel e celulose, madeira para a construção civil e setor moveleiro, carvão vegetal e lenha para produção de energia. A distribuição espacial das intervenções humanas na paisagem é fruto de uma ocupação desigual nas nove fisionomias campestres encontradas no bioma (Hasenack et al., \protect\hyperlink{ref-Hasenack}{n.d.}) (Tabela \ref{tab:fisiocamp}). Como consequência, restam 31,38\% de sua cobertura com características naturais ou seminaturais, se considerarmos o uso pecuário sobre o campo nativo como fisionomia seminatural (Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}), distribuídos em remanescentes campestres bastante fragmentados (Contreras Osorio \protect\hyperlink{ref-ContrerasOsorio2014}{2014}). As conversões anteriormente citadas e a malha viária, responsável pelo transporte de grãos, madeiras e outros bens produzidos no Rio Grande do Sul, são as principais responsáveis pela fragmentação do habitat, e podem funcionar como barreiras para certos organismos, aumentando o status de fragmentação dos remanescentes já pressionados (Teixeira \protect\hyperlink{ref-Teixeira2015}{2015}).

\begin{table}[H]

\caption[Fisionomias campestres localizadas no Bioma Pampa (Hasenack et al., dados não publicados).]{\label{tab:fisiocamp}Fisionomias campestres localizadas no Bioma Pampa (Hasenack et al., dados não publicados). 
             Relevo suave corresponde a declividades entre 3 e 8\% e relevo ondulado corresponde a declividades entre 8 e 20\%.}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{>{\centering\arraybackslash}p{3.70cm}>{\centering\arraybackslash}p{5.00cm}>{\centering\arraybackslash}p{2.25cm}>{\centering\arraybackslash}p{2.00cm}}
\toprule
Fisionomia campestre & Características principais & Área (km$^2$) & \% Pampa\\
\midrule
Campo Litorâneo & Terras baixas e relevo plano do litoral. Altitudes inferiores a 30 m. & 35.298,34 & 20,00\\
Campo Misto com Andropogôneas e Compostas & Altitudes entre 30 e 400 m com relevo suave. Depressão sedimentar com extensão predominante leste-oeste. & 35.221,13 & 19,96\\
Campo Arbustivo & Altitudes entre 30 e 400 m com relevo ondulado. Mosaico com floresta e campo onde o campo predomina. Contém áreas de solos rasos e áreas com solos profundos de baixa fertilidade. & 30.126,80 & 17,07\\
Campo com Barba-de-Bode & Altitudes entre 30 e 1.000 m e relevo suave. Solos predominantemente profundos e de baixa fertilidade. & 21.005,35 & 11,90\\
Campo com Espinilho & Altitudes entre 30 e 400 m sobre relevo suave. Predominam solos férteis imperfeitamente a mal drenados. & 13.927,30 & 7,89\\
Campo de Solos Rasos & Altitudes entre 30 e 400 m com relevo suave e solos rasos. & 13.710,59 & 7,77\\
Campo Graminoso & Altitudes entre 30 e 400 m com relevo suave. & 11.522,56 & 6,53\\
Floresta Estacional & Altitudes entre 30 e 400 m com relevo ondulado. Mosaico com floresta e campo onde a floresta predomina. & 8.752,28 & 4,96\\
Campo com Areais & Altitudes entre 30 e 400 m com relevo suave. Os solos são predominantemente arenosos, profundos, bem drenados e com baixa fertilidade. & 4.674,69 & 2,65\\
Campo Misto do Cristalino Oriental & Altitudes entre 30 e 400 m e relevo suave. & 1.164,01 & 0,66\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{delimitacao-das-bacias-de-3a-ordem-e-rede-de-drenagem}{%
\subsection*{\texorpdfstring{Delimitação das bacias de 3\textsuperscript{a} ordem e rede de drenagem}{Delimitação das bacias de 3a ordem e rede de drenagem}}\label{delimitacao-das-bacias-de-3a-ordem-e-rede-de-drenagem}}
\addcontentsline{toc}{subsection}{Delimitação das bacias de 3\textsuperscript{a} ordem e rede de drenagem}

As unidades espaciais básicas deste trabalho foram as bacias hidrográficas a montante dos rios de 3\textsuperscript{a} ordem, ou seja, a área terrestre que drena água e sedimento para os riachos de 3\textsuperscript{a} ordem. Os limites destas bacias foram obtidos a partir do modelo digital de elevação hidrologicamente consistido (MDE-HC) gerado com os pontos cotados, curvas de nível e rede hidrográfica disponíveis na Base Cartográfica Vetorial Contínua do Rio Grande do Sul - escala 1:50.000 (Hasenack and Weber \protect\hyperlink{ref-Hasenack2010b}{2010}). Para as bacias pertencentes a bacias localizadas na fronteira com outros países (por exemplo, bacia do rio Quaraí), o MDE utilizado foi o SRTM (Farr et al. \protect\hyperlink{ref-Farr2007}{2007}), disponibilizado em \url{http://earthexplorer.usgs.gov/}. Tanto o MDE-HC quanto os limites das bacias e a rede de drenagem foram processados através de uma série de etapas realizados em sistema de informação geográfica (SIG), utilizando a extensão ArcHydro 2.0, disponível para o software ArcGIS 10.3 (ESRI \protect\hyperlink{ref-ESRI2014}{2014}). Apenas as bacias localizadas em território brasileiro foram consideradas. Devido às dificuldades para gerar informações de topologia em áreas planas do terreno (Nardi et al. \protect\hyperlink{ref-Nardi2008}{2008}), as bacias localizadas na planície costeira (Campo Litorâneo; ver Figura \ref{fig:areaestudo}).

As 3359 bacias resultantes desse processo (Figura \ref{fig:locbacias3ordem}) tem áreas entre 3,15 e 159,79 km\textsuperscript{2} (média = 25,94 km\textsuperscript{2}; \(\pm\) 18,72 km\textsuperscript{2}). Somadas, correspondem a uma área de 87.126,19 km\textsuperscript{2} (49,63\% da área do bioma Pampa), das quais 71,30\% das bacias (2395) tem área inferior a 30 km\textsuperscript{2}. Para facilitar a comparação da pressão ambiental nas bacias entre as fisionomias campestres respeitando os limites biogeográficos de distribuição das espécies de peixes no Rio Grande do Sul (Stoddard \protect\hyperlink{ref-Stoddard2005a}{2004}), cada bacia foi classificada quanto a fisionomia campestre e ecorregião aquática (Abell et al. \protect\hyperlink{ref-Abell2008b}{2008}) onde está localizada (Figura \ref{fig:areaestudo}). Como algumas fisionomias campestres podem estar parcialmente contidas em mais de uma ecorregião, cada combinação de fisionomia campestre com ecorregião aquática foi chamada de subunidade regional. As fisionomias campestres analisadas neste trabalho têm áreas entre 1.164,01 e 35.221,13 km\textsuperscript{2} e representam os sistemas ecológicos que foram delimitados por similaridades em altitude, declividade, solo, vegetação e uso da terra (Tabela \ref{tab:fisiocamp}) (Hasenack et al., \protect\hyperlink{ref-Hasenack}{n.d.}).
As ecorregiões aquáticas Baixo Uruguai e Laguna dos Patos possuem 97.477,96 e 141.844,57 km\textsuperscript{2} respectivamente e foram definidas pelas similaridades na distribuição e composição de espécies de peixes de água doce, incorporando grandes padrões evolutivos e ecológicos (Abell et al. \protect\hyperlink{ref-Abell2008b}{2008}). Identificar as bacias de 3\textsuperscript{a} ordem usando mais de uma classificação quanto à região em que estão melhora a capacidade de determinar indicadores de pressão agregados no espaço, seja por questões históricas de uso e ocupação da terra ou por restrição de condições ambientais, e oferece melhor detalhamento para tomada de decisão e comparação entre condições de habitat.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/02_AreaDeEstudoSubBacias_meiaA4_v2} 

}

\caption[Localização das bacias de 3$^a$ ordem analisadas.]{Localização das bacias de 3$^a$ ordem analisadas. CArb = Campo Arbustivo; CAre = Campo com Areais; CBDB = Campo com Barba-de-Bode; CEsp = Campo com Espinilho; CSR = Campo com Solos Rasos; CGra = Campo Graminoso; CMAC = Campo Misto com Andropogôneas e Compostas; CMCO = Campo Misto do Cristalino Oriental; FE = Floresta Estacional.}\label{fig:locbacias3ordem}
\end{figure}

\hypertarget{desenvolvimento-do-indice-global-de-pressao-ambiental}{%
\subsection*{Desenvolvimento do índice global de pressão ambiental}\label{desenvolvimento-do-indice-global-de-pressao-ambiental}}
\addcontentsline{toc}{subsection}{Desenvolvimento do índice global de pressão ambiental}

O índice de pressão ambiental produzido neste trabalho foi criado baseado em três premissas: 1) cada uso humano pode ter um impacto potencial diferente no habitat e nos organismos presentes, e a magnitude do impacto é definida inicialmente, através de pesos; 2) o impacto potencial do indicador de pressão em si não tem relação com a distância em relação ao rio a que ele está localizado, ou seja, duas bacias em que uma área agrícola encontra-se distante do riacho terá o mesmo valor que uma bacia com área agrícola do mesmo tamanho adjacente ao riacho como resultado no índice global de pressão ambiental; 3) o aumento do impacto potencial do indicadores resulta em prejuízo para a biota, ou seja, sempre que houver um aumento na pressão ambiental, há uma diminuição nos valores das métricas de caracterização da comunidade utilizados. Assim, o índice global de pressão ambiental calculado neste trabalho é a soma da área/densidade dos indicadores listados a seguir ponderada pela potencialidade de impacto na ictiofauna.

Cada indicador poder exercer um efeito potencial de pressão ambiental diferente nos ambientes aquáticos (Stein, Stein, and Nix \protect\hyperlink{ref-Stein2002a}{2002}; Allan \protect\hyperlink{ref-Allan2004a}{2004}; Falcone, Carlisle, and Weber \protect\hyperlink{ref-Falcone2010}{2010}), porém não é possível estabelecer uma hierarquia de importância bem definida entre esses indicadores. Por essa razão, estabelecemos cinco configurações de ponderação distintas para os indicadores, de forma a produzir cinco cenários para diagnóstico da pressão ambiental nas bacias e que sirvam como \emph{proxy} do distúrbio antropogênico.

\hypertarget{variaveis-indicadoras-de-pressao-ambiental}{%
\subsection*{Variáveis indicadoras de pressão ambiental}\label{variaveis-indicadoras-de-pressao-ambiental}}
\addcontentsline{toc}{subsection}{Variáveis indicadoras de pressão ambiental}

Definimos o grau de pressão sobre as bacias como um índice global composto por seis variáveis que representam uso antrópico disponíveis para toda a extensão da área analisada, que estivessem em escalas compatíveis para comparação e consideradas potencialmente impactantes para o ambiente aquático. Este conjunto de variáveis inclui agricultura, área urbana, mineração, espelhos d'água maiores do que 20 ha, densidade viária e densidade de gado (Tabela \ref{tab:dados}).
Todas as fontes de dados estão disponíveis publicamente, exceto a densidade de gado, que foi fornecida pelo Instituto Brasileiro de Geografia e Estatística (IBGE; Censo Agropecuário, 2006) como números absolutos por setor censitário com pelo menos 10 informantes.

Os dados de áreas agrícolas e urbanas foram obtidos a partir do mapeamento da vegetação do Rio Grande do Sul realizados por Cordeiro and Hasenack (\protect\hyperlink{ref-Cordeiro2009a}{2009}). O mapeamento, cuja escala é de 1:50.000 e no qual somente remanescentes com um eixo maior do que 250 metros foram vetorizados, foi realizado a partir de imagens LANDSAT 5 TM e 7 ETM+ (30 m de resolução espacial), ano base 2002 e possui 32 classes de uso e cobertura de solo. Destas, cinco estão relacionadas a atividade agropecuária com potencial impacto nos ambientes aquáticos (``Agricultura sequeiro'', ``Agricultura irrigada'', ``Alagado arroz'', ``Misto campo/mato - Originalmente mata. Pastagem com domínio de campo nativo sobre área desmatada'' e ``Uso misto - cultivo em pequenas parcelas''). Estas categorias foram agrupadas em uma nova classe denominada ``Agricultura''. A rede viária disponível digitalmente na base cartográfica vetorial contínua do Rio Grande do Sul - escala 1:50.000 (Hasenack and Weber \protect\hyperlink{ref-Hasenack2010b}{2010}) foi digitalizada sobre as cartas do exercito de 1960 e está dividida em pavimentadas e não pavimentadas de acordo com as jurisdições responsáveis por sua construção e manutenção: municipal, estadual e federal. Conta também com as categorias caminho/trilhas e rede ferroviária. Embora os dados sejam oriundos de mapas da década de 1960, a pavimentação e a duplicação das rodovias foram as principais mudanças na rede viária, não a expansão da rede (Teixeira \protect\hyperlink{ref-Teixeira2015}{2015}). Todas as classes foram consideradas como igualmente impactantes.

\begin{table}[H]

\caption{\label{tab:dados}Dados utilizados para obtenção dos indicadores de pressão ambiental em bacias de 3$^a$ ordem no bioma Pampa, Brasil.}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{3.00cm}>{\raggedright\arraybackslash}p{3.00cm}>{\raggedright\arraybackslash}p{3.00cm}>{\raggedright\arraybackslash}p{3.00cm}>{\raggedright\arraybackslash}p{3.00cm}}
\toprule
Dado original & Ameaça & Escala & Ano base & Fonte\\
\midrule
 & Escoamento de pesticidas e sedimentos & 1$\colon$250.000 & 2002 & Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}\\

 & Remoção da mata ripária & 1$\colon$250.000 & 2002 & Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}\\

\multirow{-3}{3.00cm}{\raggedright\arraybackslash Áreas agrícolas} & Aumento da temperatura da água & 1$\colon$250.000 & 2002 & Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}\\
\cmidrule{1-5}
 & Aumento de superfície impermeável & 1$\colon$250.000 & 2002 & Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}\\

 & Canalização & 1$\colon$250.000 & 2002 & Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}\\

 & Alteração do fluxo & 1$\colon$250.000 & 2002 & Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}\\

\multirow{-4}{3.00cm}{\raggedright\arraybackslash Áreas urbanas} & Poluentes (esgoto doméstico, hospitalar e industrial) & 1$\colon$250.000 & 2002 & Cordeiro and Hasenack \protect\hyperlink{ref-Cordeiro2009a}{2009}\\
\cmidrule{1-5}
 & Cruzamentos & 1$\colon$50.000 & 1976-1984 & Hasenack and Weber \protect\hyperlink{ref-Hasenack2010b}{2010}\\

 & Pontes com \textit{culvets} ou pontilhões que causam barramento & 1$\colon$50.000 & 1976-1984 & Hasenack and Weber \protect\hyperlink{ref-Hasenack2010b}{2010}\\

 & Remoção da mata ripária & 1$\colon$50.000 & 1976-1984 & Hasenack and Weber \protect\hyperlink{ref-Hasenack2010b}{2010}\\

 & Aumento da temperatura da água & 1$\colon$50.000 & 1976-1984 & Hasenack and Weber \protect\hyperlink{ref-Hasenack2010b}{2010}\\

\multirow{-5}{3.00cm}{\raggedright\arraybackslash Rede viária} & Sedimentos & 1$\colon$50.000 & 1976-1984 & Hasenack and Weber \protect\hyperlink{ref-Hasenack2010b}{2010}\\
\cmidrule{1-5}
 & Extração do fundo & Não se aplica. & 2015 & DNPM \protect\hyperlink{ref-DNPM2015}{2015}\\

\multirow{-2}{3.00cm}{\raggedright\arraybackslash Mineração} & Poluição & Não se aplica. & 2015 & DNPM \protect\hyperlink{ref-DNPM2015}{2015}\\
\cmidrule{1-5}
 & Alteração do fluxo & 1$\colon$50.000 & 2003-2006 & FUNCEME \protect\hyperlink{ref-FunacaoCearencedeMeteorologiaeRecursosHidricos-FUNCEME2008a}{2008}\\

\multirow{-2}{3.00cm}{\raggedright\arraybackslash Espelhos \linebreak d'água $>$ 20 ha} & Barramento & 1$\colon$50.000 & 2003-2006 & FUNCEME \protect\hyperlink{ref-FunacaoCearencedeMeteorologiaeRecursosHidricos-FUNCEME2008a}{2008}\\
\cmidrule{1-5}
 & Aumento de nutrientes & Não se aplica. & 2006 & IBGE \protect\hyperlink{ref-IBGE2006}{2006}\\

 & Erosão das margens & Não se aplica. & 2006 & IBGE \protect\hyperlink{ref-IBGE2006}{2006}\\

 & Sedimentação do fundo & Não se aplica. & 2006 & IBGE \protect\hyperlink{ref-IBGE2006}{2006}\\

\multirow{-4}{3.00cm}{\raggedright\arraybackslash Efetivo gado} & Homogeneização dos sedimentos & Não se aplica. & 2006 & IBGE \protect\hyperlink{ref-IBGE2006}{2006}\\
\bottomrule
\end{tabular}
\end{table}

A variável Mineração foi obtida com base nos dados de processos minerários disponibilizados pelo Departamento Nacional de Produção Mineral (DNPM \protect\hyperlink{ref-DNPM2015}{2015}), que possuem caráter informativo quanto aos processos de concessão para atividade mineradora cadastrados no órgão regulador. As poligonais cadastradas estão divididas em fases de licenciamento: concessão de lavra, licenciamento, lavra garimpeira, registro de extração, requerimento de lavra, requerimento de lavra garimpeira, requerimento de licenciamento, requerimento de registro de extração, requerimento de pesquisa, autorização de pesquisa e disponibilidade. Foram incluídas nas análises as fases de concessão de lavra, licenciamento, lavra garimpeira e registro de extração. Os limites dos polígonos podem não representar precisamente os limites da extração propriamente dita por serem informados pelos próprios requerentes, e a qualidade das informações depende da metodologia técnica utilizada para o cadastro. Os limites representam a área onde o minerador pode realizar sua atividade, não a área já instalada necessariamente. Mesmo assim, as poligonais dos processos minerários nas fases consideradas representam áreas em que existe a prática da atividade de mineração ou áreas onde ela pode ser implantada em um futuro próximo.

Os dados dos efetivos de rebanho bovino, suíno e ovino do Rio Grande do Sul foram fornecidos pelo IBGE e contém no número de cabeças por setor censitário. Foram fornecidas apenas as informações dos setores censitários com 10 informantes ou mais. Os setores censitários possuem áreas muito variáveis, pois constituem a unidade territorial de coleta das operações censitárias, definido pelo IBGE, com limites físicos identificados com base na divisão político-administrativa do Brasil e no número de habitantes. Mesmo com essa variação, em geral tem área maior do que as bacias de 3\textsuperscript{a} ordem. Por isso, fizemos uma estimativa da densidade dos rebanhos nas bacias calculando o número de cabeças de bovino, ovino e suíno proporcionalmente a área do setor censitário dentro de cada bacia.

Espelhos d'água é o indicador que corresponde aos açudes e reservatórios, utilizados para dessedentação animal ou geração de energia, por exemplo, e foi obtido a partir do Mapeamento dos Espelhos d'água do Brasil com área superficial a partir de 20 hectares (Funação Cearence de Meteorologia e Recursos Hídricos - FUNCEME \protect\hyperlink{ref-FunacaoCearencedeMeteorologiaeRecursosHidricos-FUNCEME2008a}{2008}). Originalmente, o mapeamento, que utilizou imagens dos satélites LandSAT 7 e CBERS, entre os anos 2003 e 2006, estava dividido por tipo de espelho d'água: artificial (reservatório) ou natural (lagos, lagoas, outros). Utilizamos apenas os espelhos d'água classificados com artificiais.

Cada um dos indicadores abordados pode influenciar os ambientes aquáticos de diferentes formas (Tabela \ref{tab:dados}). A agricultura, por exemplo, usualmente ocupa a maior fração em uma bacia hidrográfica, enquanto áreas urbanas e outros usos ocupam uma área menor. Entretanto, estes usos podem exercer uma influência desproporcional nos ambientes aquáticos, estejam eles próximos ou distantes dos corpos d'água (Allan \protect\hyperlink{ref-Allan2004a}{2004}). Os cinco cenários diferenciam-se em função dos pesos atribuídos a cada indicador de pressão (Tabela \ref{tab:cenariospesos}). No cenário 1, todos os indicadores de pressão receberam o mesmo peso (0,17). No cenário 2, tomamos por referência os pesos utilizados em Stein, Stein, and Nix (\protect\hyperlink{ref-Stein2002a}{2002}). Em cada cenário, o somatório dos pesos de cada indicador foi sempre igual a 1. O cenário 3 representa a média dos pesos utilizados em quatro estudos: Sanderson et al. (\protect\hyperlink{ref-Sanderson2002}{2002}); Heiner et al. (\protect\hyperlink{ref-Heiner2011a}{2011}); Turak et al. (\protect\hyperlink{ref-Turak2011c}{2011}); Zhang and Chen (\protect\hyperlink{ref-Zhang2014}{2014}). Os cenários 4 e 5 foram elaboradas com o objetivo de simular quais seriam os resultados se uma única variável recebesse um peso maior (0,50), enquanto as outras fossem ponderadas da mesma forma (0,10). A variável agricultura foi a que recebeu maior peso no cenário 4 e a variável área urbana foi a definida no cenário 5. Todos os pesos somam 1 dentro de cada cenário. Por fim, os valores calculados dos índices foram padronizados para que variassem entre 0 a 1, onde 0 representa a ausência de pressão ambiental (conforme os indicadores aqui empregados) e 1 representa pressão ambiental máxima.

\begin{table}[H]

\caption{\label{tab:cenariospesos}Cenários (configurações de pesos) utilizados na ponderação dos indicadores de pressão ambiental sobre bacias de 3$^a$ ordem no bioma Pampa .}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{>{\centering\arraybackslash}p{2.50cm}>{\centering\arraybackslash}p{1.50cm}>{\centering\arraybackslash}p{1.50cm}>{\centering\arraybackslash}p{1.50cm}>{\centering\arraybackslash}p{1.50cm}c}
\toprule
 & Cenário 1 & Cenário 2 & Cenário 3 & Cenário 4 & Cenário 5\\
\midrule
Agricultura & 0,17 & 0,19 & 0,24 & 0,50 & 0,10\\
Área urbana & 0,17 & 0,25 & 0,18 & 0,10 & 0,50\\
Rede viária & 0,17 & 0,16 & 0,15 & 0,10 & 0,10\\
Mineração & 0,17 & 0,15 & 0,13 & 0,10 & 0,10\\
Espelhos d'água & 0,17 & 0,07 & 0,18 & 0,10 & 0,10\\
Gado & 0,17 & 0,19 & 0,12 & 0,10 & 0,10\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{determinacao-das-bacias-de-referencia}{%
\subsection*{Determinação das bacias de referência}\label{determinacao-das-bacias-de-referencia}}
\addcontentsline{toc}{subsection}{Determinação das bacias de referência}

Para identificar as bacias de referência, as bacias de 3\textsuperscript{a} ordem foram ranqueadas em ordem crescente quanto ao valor de cada indicador de pressão e ao valor do índice global. Em seguida, assumimos que as bacias nas quais todos os fatores de pressão medidos tiveram valor zero, foram classificadas como ``condição de distúrbio mínimo'' (MDC, abreviação para \emph{Minimum Disturbance Condition}; Stoddard et al. (\protect\hyperlink{ref-Stoddard2006}{2006})), sendo essas bacias as que representam a condição de referência ideal, mais próxima da integridade biótica. A condição mais realística, no entanto, é aquela em que se usa como referência as bacias com a melhor condição possível, isto é, aquelas que apresentam a menor presença de fatores de pressão entre as bacias avaliadas. Estas bacias foram classificadas como ``condição de menor distúrbio'' (LDC, abreviação para \emph{Least disturbed condition}; Stoddard et al. (\protect\hyperlink{ref-Stoddard2006}{2006})), descritas por um gradiente em que as bacias menos pressionadas se aproximam das bacias em condição de distúrbio mínimo em relação as bacias mais pressionadas. Neste trabalho, as bacias que estiveram entre as 10\% menos pressionadas segundo o índice global de pressão ao mesmo tempo em que apresentaram os menores valores para cada indicador separadamente em cada subunidade regional foram consideradas bacias em condição de menor distúrbio (LDC). LDC e MDC foram consideradas bacias de referência. As bacias com índice global entre 0,4 e 0,6 foram consideradas com pressão intermediária e as bacias com valores maiores do que 0,6 foram consideradas como as mais pressionadas.

\hypertarget{relacao-entre-fatores-de-pressao-e-ictiofauna}{%
\subsection*{Relação entre fatores de pressão e ictiofauna}\label{relacao-entre-fatores-de-pressao-e-ictiofauna}}
\addcontentsline{toc}{subsection}{Relação entre fatores de pressão e ictiofauna}

Para analisar se as características da ictiofauna apresentam relação com o grau de pressão ambiental na bacia, utilizamos dados de ictiofauna coletados em 52 riachos no bioma Pampa. Como indicadores de resposta da ictiofauna ao grau de pressão, utilizamos a composição e a riqueza taxonômica (riqueza rarefeita) e a riqueza funcional de espécies, além da proporção de espécies raras e comuns presentes em cada bacia amostrada. A riqueza taxonômica rarefeita foi utilizada porque o número de indivíduos amostrados por trecho de riacho foi bastante variável (de 105 a 1212 indivíduos), mesmo que a área amostrada tenha sido semelhante. As espécies raras foram definidas como as que ocorreram em menos de 10\% dos sítios (5 trechos amostrados), enquanto as espécies comuns foram aquelas que ocorreram em número de sítios igual ou superior a 50\%.

A composição de peixes foi determinada através de coleta com pesca elétrica (EFKO GmbH model FEG 1500) em 52 sítios de amostragem (cada sítio representa um riacho distinto), distribuídos por diferentes sistemas campestres e por um gradiente de antropização. Cada sítio foi amostrado uma única vez, em um trecho de 150 m no sentido jusante-montante, onde as extremidades foram bloqueadas com redes para evitar a fuga dos peixes. As coletas ocorreram entre os meses de outubro e abril, de 2013 a 2015. Todos os indivíduos coletados foram anestesiados com óleo de cravo, fixados em formol 10\% e preservados em álcool 70\% para posterior identificação em laboratório (Comissão de Ética no Uso de Animais da Universidade Federal do Rio Grande do Sul. CEUA-UFRGS; \#24433). Os trechos de rio onde foram realizadas as coletas tinham entre 0,89 e 10,26 m de largura (média = 4,85 m \(\pm\) 1,93) e entre 4 e 65,24 cm de profundidade média (média = 30,73 cm \(\pm\) 13,74).

A diversidade e a riqueza funcionais foram obtidas através de uma matriz sítio de coleta versus atributo, que foi calculada multiplicando uma matriz de espécies versus atributos por uma matriz de sítios versus espécies. Um conjunto de 13 atributos morfológicos descrevendo a função trófica, a ocupação espacial na coluna d'água e o uso do habitat: índice de compressão corporal, altura relativa, posição do olho, posição da boca, comprimento da cabeça, comprimento do pedúnculo, compressão do pedúnculo, posição da nadadeira peitoral, área da nadadeira peitoral, área da nadadeira ventral, área da nadadeira dorsal, área da nadadeira caudal e biomassa (Dala-Corte et al. \protect\hyperlink{ref-Dala-Corte2016}{2016}) (Tabela \ref{tab:atributosfuncionais}). Um valor médio foi calculado para cada atributo de cada espécie, baseado nas medidas de cinco indivíduos representando diferentes classes de tamanho de cada espécie nas amostras, sempre que possível. A composição funcional foi descrita através do valor médio dos atributos de todas as espécies presentes na comunidade (\emph{Community Weighted Mean traits}, CWM) (Lavorel et al. \protect\hyperlink{ref-Lavorel2007a}{2007}). O espaço funcional preenchido pelas espécies de cada sítio foi quantificado pelo índice de riqueza funcional descrito por Villéger, Mason, and Mouillot (\protect\hyperlink{ref-Villeger2008}{2008}). Essa medida corresponde ao volume do mínimo polígono convexo que engloba todas as espécies em um espaço com número dimensões igual ao número de atributos medidos. Estas análises foram realizadas com o pacote \texttt{FD} (Laliberté and Legendre \protect\hyperlink{ref-Laliberte2010a}{2010}) no software \texttt{R} (Team \protect\hyperlink{ref-RTeam2016}{2016}).

\begin{table}[H]

\caption[Treze atributos funcionais indicadores de uso/ocupação do habitat e comportamento alimentar.]{\label{tab:atributosfuncionais}Treze atributos funcionais indicadores de uso/ocupação do habitat e comportamento alimentar. 
             Ver Figura \ref{fig:medidas} para abreviações.}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{>{\centering\arraybackslash}p{2.80cm}>{\centering\arraybackslash}p{2.50cm}>{\centering\arraybackslash}p{8.50cm}}
\toprule
Atributo & Equação & Função\\
\midrule
Compressão do corpo & $\dfrac {BW} {BD}$ & Relacionado a mobilidade. Corpos comprimidos geralmente não encontrados em ambientes lênticos (Watson and Balon 1984).\\
Profundidade relativa do corpo & $\dfrac {BW} {SL}$ & Inversamente relacionadas a velocidade do fluxo e determina a habilidade de executar movimento vertical na coluna d'água (Gatz 1979).\\
Tamanho relativo da cabeça & $\dfrac {HL} {SL}$ & Relacionado ao tamanho da presa (Gatz 1979).\\
Posição relativa do olho & $\dfrac {EH} {HD}$ & Indica preferência de habitat vertical na coluna d'água (Gatz 1979). Varia entre 0 e 1. Valores altos indicam olhos superiores.\\
Posição relativa da boca & $\dfrac {MH} {HD}$ & Indica posição vertical na qual o peixe forrageia (Albouy et al. 2011). Varia entre 0 e 1. Valores altos indicam boca superior.\\
Comprimento relativo do pedúnculo & $\dfrac {CpL} {SL}$ & Pedúnculo caudal mais longo indica boa habilidade para o nado (Gatz 1979).\\
Compressão do pedúnculo & $\dfrac {CpH} {CpW}$ & Pedúnculo caudal comprimidos indicam atividade de nado pouco desenvolvido (Gatz 1979).\\
Posição peitoral & $\dfrac {PfP} {BD}$ & Relacionado a mobilidade (Dumay et al. 2004). Valores altos indicam nadadeiras peitorais localizadas mais próximas ao dorso em relação a parte mais ventral.\\
Área relativa da nadadeira peitoral & $\dfrac {PfL*PfH} {SL}$ & Valores altos são indicativos de espécies com hábitos bentônicos, nas quais as nadadeiras peitorais são utilizadas como ancoras para resistirem em águas rápidas (Watson and Balon 1984).\\
Área relativa da nadadeira ventral & $\dfrac {VfL * VfH} {SL}$ & Nadadeiras ventrais grandes são utilizadas como apoio para espécies bentônicas (Casatti and Castro 2006).\\
Área relativa da nadadeira caudal & $\dfrac {VfL * VfH} {SL}$ & Large caudal fins are associated to high propulsion (Gatz 1979).\\
Área relativa da nadadeira dorsal & $\dfrac {DfL * DfH} {SL}$ & Peixes que preferem fluxos rápidos geralmente tem nadadeiras dorsais pequenas (Casatti and Castro 2006).\\
Biomassa & $Weight (g)$ & Indica contribuição ao sistema via metabolismo (Albouy et al. 2011).\\
\bottomrule
\end{tabular}
\end{table}

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/03_medidas} 

}

\caption[Ilustração das 19 medidas morfométricas utilizadas para calcular os 13 atributos funcionais relacionados ao uso do hábitat e comportamento alimentar.]{Ilustração das 19 medidas morfométricas utilizadas para calcular os 13 atributos funcionais relacionados ao uso do hábitat e comportamento alimentar. SL = comprimento padrão; BD = profundidade do corpo; BW = largura do corpo; HL = comprimento da cabeça; HD = profundidade da cabeça; EH = altura do olho; MH = altura da boca; PfL = comprimento da nadadeira peitoral; PfH = atura da nadadeira peitoral; PfP = posição da nadadeira peitoral; VfL = comprimento da nadadeira ventral; VfH = altura da nadadeira ventral; DfL = comprimento da nadadeira dorsal; DfH = altura da nadadeira dorsal; CpL = comprimento do pedúnculo caudal; CpH = altura do pedúnculo caudal; CpW = largura do pedúnculo caudal; CfL = comprimento da nadadeira caudal; e CfH = altura da nadadeira caudal.}\label{fig:medidas}
\end{figure}

\hypertarget{analise-dos-dados}{%
\subsection*{Análise dos dados}\label{analise-dos-dados}}
\addcontentsline{toc}{subsection}{Análise dos dados}

A influência dos indicadores de pressão nas composições taxonômica e funcional foi determinada através de analises de redundância parcial (pRDA), utilizando bacia hidrográfica (Camaquã, Ibicuí etc.) como covariável para controlar a variação. Realizamos duas pRDA separadas, uma para composição taxonômica e outra para a composição funcional. Para estas análises, apenas as espécies que ocorreram em mais de 5 sítios foram consideradas.

Modelos lineares generalizados (GLM) foram utilizados para avaliar a relação dos indicadores de pressão e com as riquezas taxonômica e funcional, a proporção de espécies comuns e a proporção de espécies raras encontradas em cada sítio. Além disso, foram realizados separadamente modelos em que cada cenário dos índices globais de pressão fosse a variável explicativa. Os valores de riqueza taxonômica possuem distribuição aproximadamente normal. Assim, para esta variável, modelos lineares simples foram ajustados. A família de modelos de regressão Beta foi utilizada para as análises de modelos com as demais variáveis resposta, por serem representadas por valores contínuos intervalo unitário padrão (0,1). Se a variável resposta assumir os valores extremos (0,1), a seguinte transformação foi realizada: \(\dfrac {(y*(n-1)+0,5)} {n}\), onde \emph{n} é o número de riachos amostrados (Cribari-Neto and Zeileis \protect\hyperlink{ref-Cribari-Neto2010}{2010}). O pacote \texttt{vegan} (Oksanen et al. \protect\hyperlink{ref-Oksanen2016}{2016}) foi utilizado para os modelos lineares simples e o pacote \texttt{betareg} (Cribari-Neto and Zeileis \protect\hyperlink{ref-Cribari-Neto2010}{2010}) foi utilizado para os modelos cujas variáveis resposta variam entre 0 e 1.

\hypertarget{resultados}{%
\section*{Resultados}\label{resultados}}
\addcontentsline{toc}{section}{Resultados}

\hypertarget{pressao-ambiental-sobre-bacias-de-3a-ordem-no-bioma-pampa}{%
\subsection*{\texorpdfstring{Pressão ambiental sobre bacias de 3\textsuperscript{a} ordem no bioma Pampa}{Pressão ambiental sobre bacias de 3a ordem no bioma Pampa}}\label{pressao-ambiental-sobre-bacias-de-3a-ordem-no-bioma-pampa}}
\addcontentsline{toc}{subsection}{Pressão ambiental sobre bacias de 3\textsuperscript{a} ordem no bioma Pampa}

As 3359 bacias de 3\textsuperscript{a} ordem contêm pelo menos um indicador de pressão ambiental, sendo essas pressões distribuídas de forma desigual no bioma Pampa (Figura \ref{fig:pressoes} e Figura \ref{fig:boxplotsfisios}). Bacias com agricultura estão mais concentradas em partes do sudoeste onde o relevo é ondulado ou há solos rasos. As densidades de áreas urbanas e rede viária aumentam no sentido oeste-leste, ou seja, mais aglomeradas à medida que se aproximam da região metropolitana de Porto Alegre e do litoral, mais populosos do que o interior do estado. Espelhos d'água estão associados à pecuária, para dessedentação animal, e às áreas agrícolas irrigadas, encontrando-se, portando, mais concentradas no oeste do bioma. A mineração está majoritariamente localizada na região centro-sul do estado. A proporção de áreas agrícolas e a densidade de rede viária foram os fatores de pressão em média predominantes no bioma Pampa (0,38 e 0,59 respectivamente; Tabela \ref{tab:variaveisambientais}).

Aproximadamente 20\% das bacias (702) têm 70\% ou mais da sua área ocupada por agricultura, e 10,39\% (349) das bacias têm densidade viária maior do que 1 km/km\textsuperscript{2}, enquanto e a porcentagem de área ocupada pelas poligonais destinadas a mineração variou entre 0 e 99,48\% (média = 0,66 \(\pm\) 0,05). A porcentagem de área ocupada por mineração foi menor que 10\% em 98,29\% das bacias (Tabela \ref{tab:variaveisambientais}).

Não há colinearidade forte entre os indicadores de pressão ambiental, sendo agricultura e densidade de gado os indicadores mais correlacionados (r = -0,26; \emph{p} \textless{} 0,01).

Agricultura, densidade viária e de gado são os indicadores predominantes em todas as subunidades regionais (Figura \ref{fig:boxplotsfisios}). Campo de Barba-de-Bode e Floresta Estacional são as subunidades regionais com maior proporção média de área agrícola nas bacias. No Campo com Barba-de-Bode localizados no sistema da Laguna dos Patos, apenas 25\% das bacias tem menos de 71\% da área coberta por agricultura. Campo Misto com Andropogôneas e Compostas, Campo Arbustivo e Floresta Estacional tem as maiores densidades de rede viária.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/04_Pressoes_v2} 

}

\caption[Distribuição espacial dos indicadores de pressão ambiental com os limites das fisionomias campestres encontradas no bioma Pampa.]{Distribuição espacial dos indicadores de pressão ambiental com os limites das fisionomias campestres encontradas no bioma Pampa. Ver Figura \ref{fig:areaestudo} para identificação das fisionomias campestres.}\label{fig:pressoes}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics{index2_files/figure-latex/boxplotsfisios-1} 

}

\caption[Variação dos indicadores de pressão ambiental por fisionomia campestre.]{Variação dos indicadores de pressão ambiental por fisionomia campestre. Todas as variáveis variam entre 0 e 1, exceto Via (cujo valor máximo é 2,65) e Gado (cujo valor máximo é 1,92). Agr = áreas agrícolas; Urb = áreas urbanas; EA = espelhos d'água; Min = mineração; Via = rede viária; Gado = pecuária; CArb = Campo Arbustivo; CAre = Campo com Areais; CBDB = Campo com Barba-de-Bode; CEsp = Campo com Espinilho; CSR = Campo com Solos Rasos; CGra = Campo Graminoso; CMAC = Campo Misto com Andropogôneas e Compostas; CMCO = Campo Misto do Cristalino Oriental; FE = Floresta Estacional.}\label{fig:boxplotsfisios}
\end{figure}

\begin{table}[H]

\caption{\label{tab:variaveisambientais}Estatística descritiva das variáveis indicadoras de pressão ambiental.}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{>{\centering\arraybackslash}p{3.00cm}>{\centering\arraybackslash}p{3.70cm}>{\centering\arraybackslash}p{1.00cm}>{\centering\arraybackslash}p{1.00cm}>{\centering\arraybackslash}p{2.30cm}>{\centering\arraybackslash}p{1.00cm}>{\centering\arraybackslash}p{1.00cm}}
\toprule
 & Unidade & Média & Mediana & Desvio Padrão & Mínimo & Máximo\\
\midrule
Agricultura & \% área da bacia & 38,10 & 33,20 & 30,84 & 0,00 & 100,00\\
Espelhos d'água & \% área da bacia & 1,06 & 0,00 & 2,36 & 0,00 & 31,57\\
Mineração & \% área da bacia & 0,66 & 0,00 & 5,42 & 0,00 & 99,48\\
Áreas urbanas & \% área da bacia & 0,31 & 0,00 & 2,80 & 0,00 & 83,32\\
Rede viária & km/km$^2$ & 0,59 & 0,54 & 0,32 & 0,00 & 2,65\\
Densidade de gado & Número de cabeças/km$^2$ & 0,35 & 0,27 & 0,30 & 0,00 & 1,92\\
\bottomrule
\end{tabular}
\end{table}

De forma geral, há uma porção elevada de bacias de 3\textsuperscript{a} ordem com níveis intermediários a altos de pressão no bioma Pampa (Figura \ref{fig:resultscen2}). Pelo menos 38,02\% das bacias apresentam um índice global de pressão maior que 0,4 (intermediário) em todas os cenários, exceto no cenário 5, em que esse percentual corresponde a 98,99\% (Figura \ref{fig:histindpressao}).
A distribuição da frequência das bacias ao longo do gradiente de pressão não foi muito diferente entre os cenários, mas variou entre as subunidades regionais, influenciando a identidade das bacias com índice global com valores intermediários mais do que as bacias nos extremos do gradiente. A escolha dos pesos afeta a interpretação a respeito da pressão ambiental sobre as bacias nas subunidades regionais apenas nos cenários 4 e 5, pois são determinadas basicamente pela presença de agricultura e áreas urbanas respectivamente. A distribuição da frequência de bacias no gradiente de pressão é bastante variável entre subunidades regionais (Figura \ref{fig:histindpressfisios}),
podendo chegar a 85\% de bacias com nível intermediário a alto de pressão no Campo com Barba de Bode/Uruguai e na Floresta Estacional (Tabela \ref{tab:baciasresults}).
Figuram também entre as subunidades mais pressionadas o Campo com Espinilho, Campo Graminoso/Patos e Campo Misto com Andropogôneas e Compostas. Campo Arbustivo, Campo com Areais e Campos com Solos Rasos são as fisionomias menos pressionadas. Considerando que os cenários não têm variações significativas quanto ao diagnóstico global, apenas o cenário 2 foi utilizado para a descrição dos resultados deste ponto em diante, por ser o cenário com pesos variados que não tem agricultura com a maior penalidade. As figuras e histogramas referentes a todos os cenários estão no Apêndice.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/06_Results_Bacias_cenario2} 

}

\caption{Distribuição espacial do índice global de pressão ambiental resultante do cenário 2.}\label{fig:resultscen2}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/07_histograma_indpressao} 

}

\caption[Distribuição dos índices de pressão ambiental nos cinco cenários para o bioma Pampa.]{Distribuição dos índices de pressão ambiental nos cinco cenários para o bioma Pampa. A linha cinza representa a porcentagem acumulada de bacias.}\label{fig:histindpressao}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/08_histogramas_cenario2} 

}

\caption[Frequência de bacias de 3$^a$ ordem ao longo do gradiente de pressão ambiental, de acordo com o cenário 2, em cada subunidade regional do bioma Pampa.]{Frequência de bacias de 3$^a$ ordem ao longo do gradiente de pressão ambiental, de acordo com o cenário 2, em cada subunidade regional do bioma Pampa. A linha cinza representa a porcentagem acumulada de bacias. CArb = Campo arbustivo, CAre = campo com areais, CBDB = Campo com Barba-de-bode, CEsp = Campo com espinilho, CSR = campo com solos rasos, CGra = Campo Graminoso, CMAC = Campo misto com Andropogôneas e Compostas, CMCO = Campo misto do cristalino oriental, FE = Floresta Estacional.}\label{fig:histindpressfisios}
\end{figure}

Somente quatro bacias foram selecionadas como bacias de referência segundo a condição de menor distúrbio (LDC) em todos os cenários, três localizadas na subunidade regional Campo Arbustivo/Patos, e uma bacia na subunidade Floresta Estacional/Patos (Tabela \ref{tab:baciasresults}).

\begin{table}[H]

\caption[Bacias avaliadas por subunidade regional quanto ao número de bacias de referência (MDC e LDC), bacias com pressão intermediária e bacias mais pressionadas.]{\label{tab:baciasresults}Bacias avaliadas por subunidade regional quanto ao número de bacias de referência (MDC e LDC), bacias com pressão intermediária e bacias mais pressionadas. 
             Resultados correspondem ao cenário 2. 
             Valores nos parênteses referem-se a porcentagem em relação ao número total de bacias (n). 
             Os maiores valores estão destacados em negrito.}
\centering
\fontsize{10}{12}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{>{}c>{}c>{}c>{}c>{}c>{}c}
\toprule
Subunidade regional & MDC & LDC & Intermediárias & Mais Pressionadas & n\\
\midrule
CArb-Patos & 0 & \textbf{3} & 56 (8,13\%) & 6 (0,87\%) & 689\\
CArb-Uruguai & 0 & 0 & 5 (7,35\%) & 1 (1,47\%) & 68\\
FE-Patos & 0 & \textbf{1} & 165 (65,22\%) & 51 (\textbf{20,16\%}) & 253\\
CAre-Uruguai & 0 & 0 & 11 (10,89\%) & 0 & 101\\
CBDB-Patos & 0 & 0 & 59 (\textbf{73,75\%}) & 9 (11,25\%) & 80\\
CBDB-Uruguai & 0 & 0 & 229 (50,33\%) & 18 (3,96\%) & 455\\
CEsp-Uruguai & 0 & 0 & 161 (51,77\%) & 19 (6,11\%) & 311\\
CGra-Patos & 0 & 0 & 36 (46,75\%) & 1 (1,29\%) & 77\\
CGra-Uruguai & 0 & 0 & 68 (38,64\%) & 10 (5,68\%) & 176\\
CMAC-Uruguai & 0 & 0 & 85 (23,10\%) & 10 (2,72\%) & 368\\
CMAC-Patos & 0 & 0 & 169 (43,67\%) & 30 (7,75\%) & 387\\
CMCO-Patos & 0 & 0 & 4 (12,12\%) & 2 (6,06\%) & 33\\
CSR-Uruguai & 0 & 0 & 64 (17,73\%) & 7 (1,93\%) & 361\\
Bioma Pampa & 0 & 4 & 1113 (33,13\%) & 163 (4,85\%) & 3359\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item MDC = Condição de distúrbio mínimo; LDC = Condição de menor distúrbio; CArb = Campo Arbustivo; CAre = Campo com Areais; CBDB = Campo com Barba-de-Bode; CEsp = Campo com Espinilho; CSR = Campo com Solos Rasos; CGra = Campo Graminoso; CMAC = Campo Misto com Andropogôneas e Compostas; CMCO = Campo Misto do Cristalino Oriental; FE = Floresta Estacional.
\end{tablenotes}
\end{threeparttable}
\end{table}

\begin{table}[H]

\caption{\label{tab:caractbaciarefcenarios}Caracterização das bacias de referência em cada cenário de atribuição de pesos aos indicadores de pressão.}
\centering
\fontsize{10}{12}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{>{}c>{}c>{}c>{}c>{}c>{}c>{}c>{}c}
\toprule
SR & Área (km$^2$) & Agr & Via & EA & Min & Gado & Urb\\
\midrule
CArbP & 17,30 & 0 & 0,26 & 0 & 0 & 0,01 & 0\\
CArbP & 22,19 & 0 & 0,19 & 0 & 0 & 0,07 & 0\\
CArbP & 20,45 & 0 & 0,08 & 0 & 0 & 0,09 & 0\\
FE & 34,08 & 21,23 & 0,42 & 0 & 0 & 0,09 & 0\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item SR = Subunidade regional; Agr = Agricultura (\%); Via = Rede Viária (km/km$^2$); EA = Espelhos d'água < 20 ha; Min = Mineração (\%); Gado = Número de cabeças/km$^2$; Urb = Área Urbana (\%); FE = Floresta Estacional - Patos; CArbP = Campo Arbustivo - Patos.
\end{tablenotes}
\end{threeparttable}
\end{table}

As três bacias de 3\textsuperscript{a} ordem mais pressionadas foram as mesmas nos cenários 1, 2 e 3, e estão situadas nas subunidades regionais CEsp-Uruguai, e CArb-Patos. Nessas bacias, a porcentagem de agricultura foi superior a 79\% e a densidade viária é considerada alta, entre 0,89 e 1,45 km/km\textsuperscript{2} (Forman and Hersperger \protect\hyperlink{ref-Forman1996a}{1996}; Ripley, Scrimgeour, and Boyce \protect\hyperlink{ref-Ripley2005a}{2005}). No cenário 4, as três bacias mais pressionadas são compostas por um conjunto de valores altos em áreas agrícolas, gado, mineração ou rede viária, e estão localizadas nas subunidades CEsp-Uruguai e CMAC-Patos, enquanto no cenário 5 destacou as bacias dominadas por área urbana e rede viária, localizadas nas mesmas subunidades.

\hypertarget{relacoes-entre-pressao-ambiental-e-peixes}{%
\subsection*{Relações entre pressão ambiental e peixes}\label{relacoes-entre-pressao-ambiental-e-peixes}}
\addcontentsline{toc}{subsection}{Relações entre pressão ambiental e peixes}

Foram amostradas 112 espécies (Tabela \ref{tab:listaespecies}) pertencentes a 16 famílias, sendo as famílias mais ricas Characidae, Loricariidae e Cichlidae, com 38, 21 e 14 espécies respectivamente (65,17\% do número total de espécies). O número médio de espécies por riacho foi de 18,83 (max = 32, min = 6). As cinco espécies mais frequentes foram \emph{Heptapterus mustelinus} (96,15\% dos sítios), \emph{Bryconamericus iheringii} (88,46\%), \emph{Characidium pterostictum} (73,08\%), \emph{Rineloricaria stellata} (63,46\%) e \emph{Astyanax laticeps} (56,68\%). Sessenta e cinco espécies foram consideradas raras (pouco frequentes, ocorrendo em 5 riachos ou menos; 57,52\%), enquanto 10 espécies foram consideradas comuns (ocorreram em mais da metade dos riachos; 8,85\%). Cinquenta e quatro espécies (47,79\%) foram coletadas exclusivamente na ecorregião do baixo Uruguai, 17 espécies foram coletadas exclusivamente na ecorregião da Laguna dos Patos (15,04\%) e 42 espécies foram coletadas nas duas ecorregiões (37,17\%).

Os resultados da pRDA mostraram que a composição taxonômica está relacionada principalmente com agricultura e espelhos d'água. A relação entre composição taxonômica das espécies de peixes e indicadores de pressão explicou 48,77\% da variação dos dados, sendo que a maior parte dessa explicação (37,84\%) foi atribuída às bacias hidrográficas utilizadas como covariáveis. O primeiro eixo de ordenação explicou 34,37\% da variação da composição taxonômica, e o segundo eixo explicou 20\% dessa variação, os quais estão mais correlacionados com espelhos d'água (r = 0,66) e áreas agrícolas (r = -0,53) respectivamente (Figura \ref{fig:RDAtax}; Tabela \ref{tab:correlindipRDA}). Estes resultados foram considerados significativos de acordo com o teste de permutação de Monte Carlo (\emph{p} = 0,018; 999 permutações) e, portanto, permitem estabelecer correlações entre os indicadores de pressão e a ictiofauna.

O primeiro eixo de ordenação (RDA1) apresenta um gradiente associado a presença de espelhos d'água, enquanto o segundo eixo (RDA2) apresenta um gradiente associado principalmente a agricultura e mineração, mostrando uma relação inversa quanto a composição de espécies nos trechos amostrados cujas bacias apresentaram estes indicadores.

Os resultados da pRDA para composição funcional não foram considerados significativos pelo mesmo teste de permutação mencionado anteriormente (\emph{p} = 0,958; 999 permutações), não permitindo uma interpretação confiável sobre as relações entre as variáveis.

\begin{table}[H]

\caption{\label{tab:pRDAcomptax}Análise de redundância (pRDA) para relação entre composição taxonômica de peixes e indicadores de pressão.}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{>{}c>{}c>{}c>{}c}
\toprule
 & RDA1 & RDA2 & RDA3\\
\midrule
Autovalores & 0,3287 & 0,1913 & 0,1684\\
Correlações espécies-habitat & 0,84 & 0,80 & 0,69\\
\% variação explicada (cumulativa) & 34,39 & 54,40 & 72,01\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}[H]

\caption{\label{tab:correlindipRDA}Correlações dos indicadores de pressão nos primeiros eixos da análise de redundância parcial (pRDA) 
             e escores ajustados das espécies com os 10 maiores escores nos dois primeiros eixos.}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{>{}c>{}c>{}c>{}c>{}c>{}c}
\toprule
 & Variáveis &  & RDA1 & RDA2 & RDA3\\
\midrule
 & Agricultura &  & -0,26 & \textbf{-0,53} & 0,36\\

 & Gado &  & -0,35 & -0,02 & -0,29\\

 & Espelhos d'água &  & \textbf{0,66} & \textbf{-0,36} & 0,01\\

 & Rede viária &  & -0,31 & -0,04 & 0,07\\

 & Áreas urbanas &  & 0,19 & 0,02 & -0,24\\

\multirow{-6}{*}{\centering\arraybackslash Indicadores de pressão} & Mineração &  & 0,14 & \textbf{0,46} & 0,34\\
\cmidrule{1-6}
 &  & Nome abreviado & Escores & Escores & Escores\\
\cmidrule{1-6}
 & \textit{Characidium zebra} & Charzebr & \textbf{0,28} & \textbf{-0,15} & -0,04\\

 & \textit{Pseudocorydopoma doriae} & Pseudori & \textbf{0,25} & 0,08 & -0,11\\

 & \textit{Gymnogeophagus mekinos} & Gymnmeki & \textbf{0,24} & -0,02 & 0,04\\

 & \textit{Crenicichla scotti} & Crenscot & \textbf{0,24} & 0,02 & 0,05\\

 & \textit{Astyanax henseli} & Astyhens & \textbf{0,23} & 0,12 & -0,20\\

 & \textit{Gymnogeophagus rhabdotus} & Gymnrhab & \textbf{0,21} & -0,02 & -0,10\\

 & \textit{Cyanocharax alegretensis} & Cyanaleg & \textbf{0,19} & 0,02 & -0,01\\

 & \textit{Hoplias malabaricus} & Hoplmala & \textbf{-0,19} & -0,09 & -0,04\\

 & \textit{Characidium pterostictum} & Charpter & -0,19 & \textbf{0,27} & 0,00\\

 & \textit{Ancistrus taunay} & Ancitaun & \textbf{0,18} & \textbf{0,16} & 0,03\\

 & \textit{Synbranchus marmoratus} & Synbmarm & \textbf{0,17} & \textbf{-0,14} & -0,06\\

 & \textit{Astyanax xiru} & Astyxiru & 0,03 & \textbf{0,22} & 0,12\\

 & \textit{Scleronema minutum} & Scleminu & 0,10 & \textbf{0,18} & -0,01\\

 & \textit{Astyanax jacuhiensis} & Astyjacu & -0,04 & \textbf{-0,16} & \textbf{-0,18}\\

 & \textit{Crenicichla lepidota} & Crenlepi & 0,03 & \textbf{-0,15} & -0,13\\

\multirow{-16}{*}{\centering\arraybackslash Espécies} & \textit{Rineloricaria cadeae} & Rinecade & 0,02 & \textbf{0,14} & \textbf{-0,15}\\
\bottomrule
\end{tabular}
\end{table}

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/09_RDA_PA3} 

}

\caption[Análise de redundância realizada entre a composição taxonômica de espécies de peixes e os indicadores de pressão.]{Análise de redundância realizada entre a composição taxonômica de espécies de peixes e os indicadores de pressão. Os nomes das espécies estão abreviados e suas correspondências encontram-se na Tabela \ref{tab:correlindipRDA}.}\label{fig:RDAtax}
\end{figure}

Três indicadores de pressão apresentaram relação com a riqueza taxonômica: áreas urbanas, espelhos d'água e agricultura (Tabela \ref{tab:coefbetaindriqtax}). O modelo explicou 26,90\% da variação da variável resposta, mas as estimativas para espelhos d'água e áreas urbanas foram inverossímeis devido à baixa quantidade de bacias amostradas com presença desses indicadores (sobreajuste). Assim, não consideramos estas relações interpretáveis. A agricultura está relacionada negativamente com riqueza taxonômica (Figura \ref{fig:RiqRarAgr}).

Nenhum indicador de pressão ou cenário teve relação significativa com riqueza funcional (Tabela \ref{tab:coefbetaindriqfunc}). Apesar disso, há um padrão de diminuição da riqueza funcional em relação ao índice global de pressão, isto é, a variação nos valores de riqueza funcional em bacias com baixa pressão ambiental é maior do que nas bacias com pressão elevada (Figura \ref{fig:RiqFuncCen}).

\begin{table}[H]
\caption{\label{tab:coefbetaindriqtax}Coeficientes beta para o modelo linear generalizado do efeito de indicadores de pressão sobre riqueza taxonômica de 
  peixes em riachos do Pampa. Cinco modelos diferentes foram realizados utilizando os cenários como variável explicativa, mas 
  seus coeficientes beta estão descritos em uma única tabela para facilitar a representação.}

\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{c>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.5in}>{}p{0.5in}}
\toprule
Indicadores de pressão & Beta & Erro padrão & \textit{p-value}\\
\midrule
Intercepto & 14,53 & 0,55 & <0,01\\
Agricultura & \textbf{-3,86} & 2,25 & \textbf{0,05}\\
Espelhos d'água & \textbf{169,48} & 70,80 & \textbf{0,02}\\
Rede viária & 0,17 & 2,55 & 0,95\\
Gado & 1,46 & 2,13 & 0,50\\
Mineração & -25,55 & 644,49 & 0,97\\
Áreas urbanas & \textbf{1261,45} & 517,67 & \textbf{0,02}\\
\bottomrule
\end{tabular}
\centering
\begin{tabular}[t]{cccc}
\toprule
Cenários & Beta & Erro padrão & \textit{p-value}\\
\midrule
1 & 1,125 & 4,154 & 0,78\\
2 & 1,23 & 4,103 & 0,76\\
3 & $-$0,41 & 3,26 & 0,90\\
4 & $-$0,91 & 2,59 & 0,73\\
5 & 2,028 & 8,33 & 0,73\\
\bottomrule
\end{tabular}
\end{table}

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/10_plot_riqrar_Agr} 

}

\caption[Relação entre Agricultura (\%) e riqueza taxonômica.]{Relação entre Agricultura (\%) e riqueza taxonômica. As linhas pontilhadas representam o intervalo de confiança 95\%.}\label{fig:RiqRarAgr}
\end{figure}

\begin{table}[H]
\caption{\label{tab:coefbetaindriqfunc}Coeficientes beta para o modelo linear generalizado do efeito de indicadores de pressão sobre riqueza funcional de
  peixes em riachos do Pampa. 
  Cinco modelos diferentes foram realizados utilizando os cenários como variável explicativa, mas seus coeficientes betas estão 
  descritos em uma única tabela para facilitar a representação.}

\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{c>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.5in}>{}p{0.5in}}
\toprule
Indicadores de pressão & Beta & Erro padrão & \textit{p-value}\\
\midrule
Intercepto & -2,26 & 0,13 & <0,01\\
Agricultura & -0,44 & 0,46 & 0,34\\
Espelhos d'Ã¡gua & 43,13 & 11,39 & 0,53\\
Rede viÃ¡ria & -0,10 & 0,51 & 0,83\\
Gado & 0,21 & 0,42 & 0,61\\
MineraÃ§Ã£o & 45,92 & 121,34 & 0,70\\
Ãrea Urbana & 53,46 & 48,94 & 0,27\\
\bottomrule
\end{tabular}
\centering
\begin{tabular}[t]{cccc}
\toprule
Cenários & Beta & Erro padrão & \textit{p-value}\\
\midrule
1 & -0,83 & 0,82 & 0,31\\
2 & -0,80 & 0,82 & 0,98\\
3 & -0,97 & 0,81 & 0,14\\
4 & -0,89 & 0,58 & 0,26\\
5 & -1.67 & 1,79 & 0,31\\
\bottomrule
\end{tabular}
\end{table}

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/11_plot_riquezafuncionalXcenarios} 

}

\caption{Riqueza funcional em relação aos índices globais de pressão ambiental nos cinco cenários.}\label{fig:RiqFuncCen}
\end{figure}

Nenhum indicador de pressão ou cenário apresentou relação com a proporção de espécies comuns (Tabela \ref{tab:coefbetaindespcom}) e raras (Tabela \ref{tab:coefbetaindesprar}).

\begin{table}[H]
\caption{\label{tab:coefbetaindespcom}Coeficientes beta para o modelo linear generalizado do efeito de indicadores de pressão sobre porcentagem de espécies 
  comuns de peixes em riachos do Pampa. Cinco modelos diferentes foram realizados utilizando os cenários como variável explicativa, 
  mas seus coeficientes betas estão descritos em uma única tabela para facilitar a representação.}

\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{c>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.5in}>{}p{0.5in}}
\toprule
Indicadores de pressão & Beta & Erro padrão & \textit{p-value}\\
\midrule
Intercepto & -0,48 & 0,07 & <0,01\\
Agricultura & 0,13 & 0,30 & 0,65\\
Espelhos d'Ã¡gua & -18,13 & 10,28 & 0,12\\
Gado & -0,30 & 0,29 & 0,30\\
Rede viÃ¡ria & 0,41 & 0,34 & 0,23\\
MineraÃ§Ã£o & -8,49 & 87,54 & 0,92\\
Ãreas urbanas & -26,91 & 41,35 & 0,52\\
\bottomrule
\end{tabular}
\centering
\begin{tabular}[t]{cccc}
\toprule
Cenários & Beta & Erro padrão & \textit{p-value}\\
\midrule
1 & 0,26 & 0,55 & 0,63\\
2 & 0,23 & 0,55 & 0,67\\
3 & 0,31 & 0,43 & 0,49\\
4 & 0,27 & 0,34 & 0,42\\
5 & 0,52 & 1,12 & 0,64\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}[H]
\caption{\label{tab:coefbetaindesprar}Coeficientes beta para o modelo linear generalizado do efeito de indicadores de pressão sobre porcentagem de
  espécies comuns de peixes em riachos do Pampa. Cinco modelos diferentes foram realizados utilizando os cenários 
  como variável explicativa, mas seus coeficientes betas estão descritos em uma única tabela para facilitar a representação.}

\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{c>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.5in}>{}p{0.5in}}
\toprule
Indicadores de pressão & Beta & Erro padrão & \textit{p-value}\\
\midrule
Intercepto & -1,80 & 0,12 & <0,01\\
Agricultura & 0,06 & 0,44 & 0,89\\
Espelhos d'Ã¡gua & 39,06 & 11,95 & 0,20\\
Gado & 0,17 & 0,42 & 0,68\\
Rede viÃ¡ria & -0,45 & 0,51 & 0,38\\
MineraÃ§Ã£o & -218,27 & 155,54 & 0,16\\
Ãreas urbanas & -27,20 & 59,66 & 0,64\\
\bottomrule
\end{tabular}
\centering
\begin{tabular}[t]{cccc}
\toprule
Cenários & Beta & Erro padrão & \textit{p-value}\\
\midrule
1 & -0,30 & 0,82 & 0,71\\
2 & -0,29 & 0,81 & 0,72\\
3 & -0,56 & 0,66 & 0,39\\
4 & -0,62 & 0,52 & 0,23\\
5 & -0,70 & 1,65 & 0,67\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{discussao}{%
\section*{Discussão}\label{discussao}}
\addcontentsline{toc}{section}{Discussão}

O diagnóstico de pressão ambiental mostrou que o bioma Pampa contém uma porção elevada das bacias hidrográficas de 3\textsuperscript{a} ordem com níveis intermediários a altos de pressão: em torno de 38\% das bacias, dependendo do cenário, sofre pressão ambiental relativamente intensa por pelo menos um indicador. Mesmo com a variação dessa proporção entre as subunidades regionais, a maioria das fisionomias campestres é composta apenas por bacias que apresentam pressão ambiental relativamente intensa por pelo menos um indicador, enfraquecendo a possibilidade de servirem como referência para conservação ou restauração dos campos. Apenas duas das 12 subunidades ainda abrigam bacias de referência, as quais representam menos de 1\% do número de bacias (e da área de bacias de 3\textsuperscript{a} ordem) em cada fisionomia campestre (Tabela \ref{tab:baciasresults}).

A comparação entre as cinco configurações de pesos não resultou em diagnósticos com diferenças notáveis quanto a condição de pressão das fisionomias campestres (com exceção do cenário 5; Figura \ref{fig:histogramascenario5}), implicando em baixa sensibilidade dos resultados à atribuição de pesos dos fatores. Mudar a importância relativa de um indicador, entretanto, pode mudar a identificação das bacias em condição intermediária, especialmente aquelas que não apresentam um único indicador de pressão predominante, fragilizando o processo de destinação do investimento para conservação. Agricultura, espelhos d'água e densidade da rede viária foram os direcionadores de pressão nos três sistemas ecológicos mais pressionados: Campo com Espinilho, Floresta Estacional e Campo com barba-de-bode, mas o gradiente de pressão ambiental como um todo foi determinado principalmente pela presença da agricultura, cuja grande magnitude fez com que as bacias menos pressionadas tendessem a ser aquelas localizadas nas fisionomias com menor vocação para atividades agrícolas.

A riqueza taxonômica foi mais fortemente relacionada com agricultura, uma relação com resultados que, como neste trabalho, tipicamente indicam efeitos negativos sobre a ictiofauna (Roth, Allan, and Erickson \protect\hyperlink{ref-Roth1996}{1996}; Sala \protect\hyperlink{ref-Sala2000a}{2000}, @Allan2004a), mas que também pode apresentar efeitos positivos sobre a riqueza de peixes (Harding et al. \protect\hyperlink{ref-Harding1998}{1998}). A remoção da cobertura vegetal ripária e o aumento da entrada de nutrientes oriunda dos resíduos agrícolas e urbanos causam alterações no ambiente, como o aparecimento de macrófitas (Burrell et al. \protect\hyperlink{ref-Burrell2014}{2014}), e cria condições para que espécies nativas tipicamente encontradas em rios maiores e espécies mais tolerantes a qualidade, temperatura e modificações na estrutura do habitat ocupem esses ambientes (Scott and Helfman \protect\hyperlink{ref-Scott2001}{2001}; Dala-Corte et al. \protect\hyperlink{ref-Dala-Corte2016}{2016}). O que parece ser um efeito positivo de aumento da riqueza em primeira instância, pode resultar em subsequente diminuição no número de espécies causado pelo desaparecimento das espécies mais sensíveis a essas novas condições (Daga et al. \protect\hyperlink{ref-Daga2012a}{2012}). A agricultura e os espelhos d'água também estiveram relacionados com a composição taxonômica, evidenciando que espécies mais tolerantes, como \emph{Synbranchus marmoratus} e \emph{Characidium zebra} estão positivamente relacionadas com a presença de espelhos d'água, diferentemente de \emph{Characidim pterostictum}, geralmente encontrada em arroios e rios com correnteza, fundo rochoso e águas claras (Buckup and Reis \protect\hyperlink{ref-Buckup1997}{1997}), no extremo oposto deste gradiente.
Embora os outros indicadores de pressão não tenham sido relacionados com as características da ictiofauna, o aumento da área urbanizada pode promover diferenças na composição e estrutura das assembleias de peixe, onde apenas as espécies tolerantes e não-nativas tendem a ocorrer (Daga et al. \protect\hyperlink{ref-Daga2012a}{2012}). Além da fragmentação promovida pelo barramento da água, os espelhos d'água promovem um novo ambiente tipicamente lêntico (Clavero and Hermoso \protect\hyperlink{ref-Clavero2011}{2011}), que ocupa uma grande área (144.836,220 ha em 2407 reservatórios; Funação Cearence de Meteorologia e Recursos Hídricos - FUNCEME (\protect\hyperlink{ref-FunacaoCearencedeMeteorologiaeRecursosHidricos-FUNCEME2008a}{2008})). Clavero and Hermoso (\protect\hyperlink{ref-Clavero2011}{2011}) não encontraram diferença na riqueza de espécies em riachos livres ou com reservatórios, mas os riachos diferenciaram-se quanto à composição das espécies: os riachos barrados abrigavam mais espécies invasoras e menos espécies nativas. Os efeitos da agricultura e dos barramentos por reservatórios lentamente eliminam a heterogeneidade natural dos riachos, agindo como reguladores artificiais da vazão (Poff et al. \protect\hyperlink{ref-Poff2007}{2007}; Dala-Corte et al. \protect\hyperlink{ref-Dala-Corte2016}{2016}). Nestes locais predominam as espécies cujas características indicam ocuparem e se alimentarem na coluna d'água, em habitats mais tipicamente com pouca correnteza (espécies com corpo e pedúnculo caudal comprimidos, olhos grandes, posição da boca terminal a superior e cabeça grande).

A necessidade de dados que cobrissem toda a área do bioma Pampa foi um limitante na determinação dos indicadores que seriam usados neste trabalho devido a disponibilidade dos dados. Apesar disso, o conjunto de indicadores utilizados neste trabalho contempla as principais atividades causadoras de pressão nas bacias do bioma Pampa. Uma abordagem alternativa poderia diferenciar pressões causadas por diferentes tipos de culturas agrícolas, de produção mineral ou estradas com diferentes fluxos de veículos, que, somados, comporiam um novo indicador mais complexo (p.ex. Stein, Stein, and Nix (\protect\hyperlink{ref-Stein2002a}{2002})). O uso de abordagens não-lineares, de outros indicadores de pressão (nutrientes, como nitrogênio e fósforo, porcentagem de conversão e presença do gado especificamente na zona ripária), de outras variáveis resposta (grau de tolerância das espécies Esselman et al. (\protect\hyperlink{ref-Esselman2011b}{2011})), ou avaliação multi-escala (Roth, Allan, and Erickson \protect\hyperlink{ref-Roth1996}{1996}; Sály et al. \protect\hyperlink{ref-Saly2009}{2009}; Dala-Corte et al. \protect\hyperlink{ref-Dala-Corte2016}{2016}) podem ser pontos a serem considerados para compreender e caracterizar melhor as relações entre as alterações antropogênicas em bacias hidrográficas e seus efeitos sobre biodiversidade, de forma melhor sustentar medidas de conservação ou restauração.

A ausência de relação entre o índice global de pressão ambiental e os descritores da comunidade de peixes, assim como entre a riqueza funcional e os indicadores de pressão mostraram que nem sempre as relações entre a biodiversidade e os fatores de pressão são lineares e diretas. Ainda assim, podemos inferir um padrão de diminuição da riqueza funcional com o aumento da pressão em todos os cenários, determinado especialmente pela agricultura e pela densidade de gado (Figura \ref{fig:RiqFuncCen}). Herbst et al. (\protect\hyperlink{ref-Herbst2012}{2012}), utilizando diferentes abordagens para medir o efeito do pastoreio, encontraram uma relação de diminuição da riqueza de invertebrados aquáticos em riachos com o aumento nos níveis dessa atividade. O efeito da agricultura sobre a riqueza de espécies de peixe é variável, dependente de escala e pode ser dar por diferentes mecanismos.

O fato de a composição taxonômica dos peixes estar mais relacionada com as bacias onde estão localizadas do que com os indicadores de pressão mostra que há a um efeito importante de fatores biogeográficos históricos na formação do pool de espécies de diferentes bacias, aparentemente maior do que efeitos associados aos fatores de pressão ambiental. Logo, a complexidade geográfica do bioma Pampa é um fator importante a ser considerado e não surpreende que possa determinar, por si só, grande parte da variação da comunidade aquática, pois tal heterogeneidade determina barreiras geográficas e filtros ambientais não-antropogênicos para a distribuição das espécies.

As variáveis fisiográficas e os usos antrópicos raramente têm efeitos isolados sobre o habitat e sobre a biota, mas produzem efeitos sinérgicos e cumulativos tanto no entorno dos ambientes aquáticos quanto em seus interiores, podendo interagir entre si. A baixa variação explicada pelos indicadores de pressão individuais, ainda que estatisticamente significativos, indica baixa sensibilidade das variáveis resposta deste estudo às influências antropogênicas em uma área tão ampla. Existem diversos fatores que influenciam as características das comunidades locais: histórico de distúrbios dos locais, variações de escala espacial mais restrita entre locais (em função da declividade, posição na rede de drenagem) (p.ex Dala-Corte (\protect\hyperlink{ref-Dala-Corte2016a}{1979})).
O fator biogeográfico regional foi mais importante que os fatores de pressão na relação com a composição taxonômica. Além disso, há um descompasso entre a data das coletas e as informações de uso do solo, que pode ser responsável por uma subestimativa da proporção de agricultura e áreas urbanas nas bacias.

\hypertarget{implicacoes-para-gestao-conservacao-e-recuperacao}{%
\subsection*{Implicações para gestão: conservação e recuperação}\label{implicacoes-para-gestao-conservacao-e-recuperacao}}
\addcontentsline{toc}{subsection}{Implicações para gestão: conservação e recuperação}

O diagnóstico de pressão ambiental do bioma Pampa e a identificação das bacias de referência mostram o quanto a influência humana está disseminada em todas as fisionomias campestres. Isso nos indica que esforços de conservação devem ser focados no gerenciamento das atividades antrópicas, especialmente na desaceleração das conversões da cobertura do solo para agricultura, espelhos d'água e áreas urbanas. Embora não contemple uma lista completa das ameaças existentes para o bioma Pampa e seus riachos, este trabalho oferece uma importante base para entender como estas pressões se distribuem e para onde os esforços para conservação e gerenciamento da biodiversidade podem ser direcionados. A visualização das bacias segundo um gradiente de pressão resultante deste trabalho dispõe uma forma intuitiva de descrever a intensidade de pressão nas bacias, facilitando comparações entre condições posicionadas em um \emph{continuum}. Isolar os sítios das pressões antrópicas é muito pouco factível e, assim, a melhoria das condições dos ambientes aquáticos depende de melhores práticas de gestão e melhorias na configuração e gerenciamento da paisagem. Isso demanda que haja planejamento e gestão regionalizada por órgãos gestores do ambiente, e que este oriente a gestão e o manejo ao nível de propriedades rurais e de pequenas unidades hidrográficas, que são as escalas geográficas em que a prática do manejo e da restauração podem ser efetivadas.

Para que as ações de gerenciamento e restauração sejam efetivas, deve-se diagnosticar a origem e/ou causa das ameaças além de mapeá-las, o que requer um entendimento mais profundo dos mecanismos através dos quais o uso da terra impacta os ecossistemas aquáticos. Diversos estudos tem sido publicados nesse sentido (Allan \protect\hyperlink{ref-Allan2004a}{2004}; Ripley, Scrimgeour, and Boyce \protect\hyperlink{ref-Ripley2005a}{2005}; Daniel et al. \protect\hyperlink{ref-Daniel2015}{2015}; Dala-Corte et al. \protect\hyperlink{ref-Dala-Corte2016}{2016}), mas pouco (ou superficialmente) são incorporados nos estudos para determinação de bacias de referência e áreas prioritárias para conservação.

As ações para conservação e a escolha de seus alvos dependem da intensidade da influência humana nas bacias. Quando o grau de pressão ambiental é elevado (Figura \ref{fig:ImplicPior}),
as ações são limitadas pela proporção de áreas alvo para conservação disponíveis. O planejamento pode abordar restauração dos ecossistemas, conectividade dos fragmentos remanescentes e reintrodução das espécies (ou controle populacional, quando o aumento da população torna-se um problema originado pelo aumento do impacto; p.~ex: espécies invasoras). Onde o grau de pressão é relativamente mais baixo (Figura \ref{fig:ImplicRef}), nas bacias de referência, por exemplo, uma grande variedade de ações e alvos de conservação pode ser possível, podendo incluir a criação e o gerenciamento de áreas com uso humano limitado (ou seja, áreas protegidas) ou conscientização junto as comunidades humanas locais. Bacias hidrográficas com níveis intermediários de influência humana (Figura \ref{fig:ImplicInterm}) são passíveis de estratégias mistas de conservação e restauração, que são mais eficientes quando planejadas em escala regional ou de paisagem (Noss \protect\hyperlink{ref-Noss1983}{1983}). Nessas áreas, frequentemente um fator predomina sobre os outros e, assim, as medidas de conservação poderiam ser planejadas no sentido destes usos.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/12_Implicacoes_piores} 

}

\caption{Proporção da área de bacias hidrográficas de 3$^a$ ordem mais pressionadas (índice global maior que 0,6) nas fisionomias campestres.}\label{fig:ImplicPior}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/13_Implicacoes_referencias} 

}

\caption{Proporção da área de bacias hidrográficas de 3$^a$ ordem de referência nas fisionomias campestres.}\label{fig:ImplicRef}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/14_Implicacoes_intermediarias} 

}

\caption{Proporção da área de bacias hidrográficas de 3$^a$ ordem com grau de pressão intermediária (índice global entre 0,4 e 0,6) nas fisionomias campestres.}\label{fig:ImplicInterm}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figuras/15_Implicacoes_mapacompleto} 

}

\caption{Bacias hidrográficas de 3$^a$ ordem classificadas conforme grau de pressão no bioma Pampa. }\label{fig:MapaCompl}
\end{figure}

\hypertarget{consideracoes-finais}{%
\section*{Considerações finais}\label{consideracoes-finais}}
\addcontentsline{toc}{section}{Considerações finais}

Nossos resultados mostraram que considerar a pressão no bioma Pampa como um todo mascara possíveis variações entre subunidades regionais que podem estar mais pressionadas do que outras. A proporção de bacias hidrográficas com grau de pressão intermediário a alto é mais elevada dentro de algumas fisionomias campestres do que considerando todas as bacias do bioma Pampa somadas, e a existência de relação entre fator de pressão com a ictiofauna depende da variável resposta escolhida. Mapeamentos regionais geralmente não seguem uma especificidade geográfica e de precisão de detalhe que deve ser assumida em estudos focados na conservação da biodiversidade, especialmente em estudos envolvendo ambientes aquáticos, tradicionalmente negligenciados nas políticas de gerenciamento que abordam muito mais as causas e consequências no ambiente terrestre. A multiplicidade de fontes de informação por iniciativas nacionais implica em diferenças no método de geração dos mapeamentos e contribuem para a incerteza dos resultados. Portanto, observar e considerar tais incertezas durante a execução dos estudos é extremamente importante, porque uma das formas de lidar com essa dificuldade ao relacionar informações originadas de formas diferentes, aumentando o realismo da avaliação, é representar todos os indicadores possíveis do conjunto de ameaças presentes nos habitats aquáticos. Iniciativas estaduais com objetivos mais específicos e focados na necessidade e no planejamento regional poderiam ser fomentadas, utilizando proxies quando a informação direta não estiver disponível, porém em nosso estudo mostramos que nem sempre as relações com características ecológicas são simples ou diretas. Mesmo informações adquiridas na fonte primária (como o efetivo de gado, neste trabalho), são obtidas com unidade espacial pouco útil para fins de gerenciamento de bacias.

\newpage

\hypertarget{referencias}{%
\section*{Referências}\label{referencias}}
\addcontentsline{toc}{section}{Referências}

\hypertarget{refs}{}
\leavevmode\hypertarget{ref-Abell2008b}{}%
Abell, Robin, Michele L. Thieme, Carmen Revenga, Mark Bryer, Maurice Kottelat, Nina Bogutskaya, Brian Coad, et al. 2008. ``Freshwater Ecoregions of the World: A New Map of Biogeographic Units for Freshwater Biodiversity Conservation.'' \emph{Bioscience} 58 (5): 403--14. \url{https://doi.org/10.1641/B580507}.

\leavevmode\hypertarget{ref-Allan2004a}{}%
Allan, J. David. 2004. ``Landscapes and Riverscapes: The Influence of Land Use on Stream Ecosystems.'' \emph{Annu. Rev. Ecol. Evol. Syst.} 35 (1): 257--84. \url{https://doi.org/10.1146/annurev.ecolsys.35.120202.110122}.

\leavevmode\hypertarget{ref-Allan2013}{}%
Allan, J. D., P. B. McIntyre, S D P Smith, B S Halpern, G L Boyer, A. Buchsbaum, G. A. Burton, et al. 2013. ``Joint analysis of stressors and ecosystem services to enhance restoration effectiveness.'' \emph{Proc. Natl. Acad. Sci.} 110 (1): 372--77. \url{https://doi.org/10.1073/pnas.1213841110}.

\leavevmode\hypertarget{ref-Andrade2015a}{}%
Andrade, Bianca O., Christiane Koch, Ilsi I. Boldrini, Eduardo Vélez-Martin, Heinrich Hasenack, Julia-Maria Hermann, Johannes Kollmann, Valério D. Pillar, and Gerhard E. Overbeck. 2015. ``Grassland degradation and restoration: a conceptual framework of stages and thresholds illustrated by southern Brazilian grasslands.'' \emph{Nat. Conserv.} 13 (2): 95--104. \url{https://doi.org/10.1016/j.ncon.2015.08.002}.

\leavevmode\hypertarget{ref-Angermeier2004a}{}%
Angermeier, Paul L., Andrew P. Wheeler, and Amanda E. Rosenberger. 2004. ``A Conceptual Framework for Assessing Impacts of Roads on Aquatic Biota.'' \emph{Fisheries} 29 (12): 19--29. \href{https://doi.org/10.1577/1548-8446(2004)29\%5B19:ACFFAI\%5D2.0.CO;2}{https://doi.org/10.1577/1548-8446(2004)29{[}19:ACFFAI{]}2.0.CO;2}.

\leavevmode\hypertarget{ref-Brooks2006}{}%
Brooks, T. M., R. A. Mittermeier, G. A. B. da Fonseca, J. Gerlach, M. Hoffmann, J. F. Lamoreux, C. G. Mittermeier, J. D. Pilgrim, and A. S. L. Rodrigues. 2006. ``Global Biodiversity Conservation Priorities.'' \emph{Science (80-. ).} 313 (5783): 58--61. \url{https://doi.org/10.1126/science.1127609}.

\leavevmode\hypertarget{ref-Buckup1997}{}%
Buckup, Paulo A, and Roberto E Reis. 1997. ``Characidiin Genus Characidium (Teleostei, Characiformes) in Southern Brazil, with Description of Three New Species.'' \emph{Copeia} 1997 (3): 531. \url{https://doi.org/10.2307/1447557}.

\leavevmode\hypertarget{ref-Burrell2014}{}%
Burrell, Teresa K., Jonathan M. O'Brien, S. Elizabeth Graham, Kevin S. Simon, Jon S. Harding, and Angus R. McIntosh. 2014. ``Riparian shading mitigates stream eutrophication in agricultural catchments.'' \emph{Freshw. Sci.} 33 (1): 73--84. \url{https://doi.org/10.1086/674180}.

\leavevmode\hypertarget{ref-Clavero2011}{}%
Clavero, Miguel, and Virgilio Hermoso. 2011. ``Reservoirs promote the taxonomic homogenization of fish communities within river basins.'' \emph{Biodivers. Conserv.} 20 (1): 41--57. \url{https://doi.org/10.1007/s10531-010-9945-3}.

\leavevmode\hypertarget{ref-ContrerasOsorio2014}{}%
Contreras Osorio, Ricardo. 2014. ``The Effect of Landscape Configuration and Dispersal Capacity on Habitat Availability for Birds: An Assessment for Campos Grasslands in Southern Brazil.'' PhD thesis, Universidade Federal do Rio Grande do Sul.

\leavevmode\hypertarget{ref-Cordeiro2009a}{}%
Cordeiro, José Luís Passos, and Heinrich Hasenack. 2009. ``Cobertura vegetal atual do Rio Grande do Sul.'' In \emph{Campos Sulinos Conserv. E Uso Sustentável Da Biodiversidade}, edited by Valério de Patta Pillar, Sandra Cristina Müller, Zélia Maria de Souza Castilhos, and Aino Victor Ávila Jaques, 285--99. Brasilia: Ministério do Meio Ambiente.

\leavevmode\hypertarget{ref-Cribari-Neto2010}{}%
Cribari-Neto, Francisco, and Achim Zeileis. 2010. ``Beta Regression in R.'' \emph{J. Stat. Softw.} 34 (2). \url{https://doi.org/10.18637/jss.v034.i02}.

\leavevmode\hypertarget{ref-Daga2012a}{}%
Daga, Vanessa Salete, Éder André Gubiani, Almir Manoel Cunico, and Gilmar Baumgartner. 2012. ``Effects of abiotic variables on the distribution of fish assemblages in streams with different anthropogenic activities in southern Brazil.'' \emph{Neotrop. Ichthyol.} 10 (3): 643--52. \url{https://doi.org/10.1590/S1679-62252012000300018}.

\leavevmode\hypertarget{ref-Dala-Corte2016a}{}%
Dala-Corte, Renato B. 1979. ``Efeitos de processos regionais e locais sobre comunidades, populações e interações em peixes de riachos.'' Doutorado, Universidade Federal do Rio Grande do Sul.

\leavevmode\hypertarget{ref-Dala-Corte2016}{}%
Dala-Corte, Renato B., Xingli Giam, Julian D. Olden, Fernando G. Becker, Taís de F. Guimarães, and Adriano S. Melo. 2016. ``Revealing the pathways by which agricultural land-use affects stream fish communities in South Brazilian grasslands.'' \emph{Freshw. Biol.} 61 (11): 1921--34. \url{https://doi.org/10.1111/fwb.12825}.

\leavevmode\hypertarget{ref-Daniel2015}{}%
Daniel, Wesley M., Dana M. Infante, Robert M. Hughes, Yin-Phan Tsang, Peter C. Esselman, Daniel Wieferich, Kyle Herreman, Arthur R. Cooper, Lizhu Wang, and William W. Taylor. 2015. ``Characterizing coal and mineral mines as a regional source of stress to stream fish assemblages.'' \emph{Ecol. Indic.} 50 (September 2015): 50--61. \url{https://doi.org/10.1016/j.ecolind.2014.10.018}.

\leavevmode\hypertarget{ref-DNPM2015}{}%
DNPM. 2015. ``Sistema de Informações Geográficas da Mineração - SIGMINE.'' \url{http://sigmine.dnpm.gov.br/webmap/}.

\leavevmode\hypertarget{ref-Dudgeon2006a}{}%
Dudgeon, David, Angela H Arthington, Mark O Gessner, Zen-Ichiro Kawabata, Duncan J Knowler, Christian Lévêque, Robert J Naiman, et al. 2006. ``Freshwater biodiversity: importance, threats, status and conservation challenges.'' \emph{Biol. Rev.} 81 (02): 163. \url{https://doi.org/10.1017/S1464793105006950}.

\leavevmode\hypertarget{ref-ESRI2014}{}%
ESRI. 2014. \emph{ArcGIS 10.3}. Environmental Systems Research Institute, Inc. Environmental Systems Research Institute, Inc.

\leavevmode\hypertarget{ref-Esselman2011b}{}%
Esselman, Peter C., Dana M. Infante, Lizhu Wang, Dayong Wu, Arthur R. Cooper, and William W. Taylor. 2011. ``An Index of Cumulative Disturbance to River Fish Habitats of the Conterminous United States from Landscape Anthropogenic Activities.'' \emph{Ecol. Restor.} 29 (1-2): 133--51. \url{https://doi.org/10.3368/er.29.1-2.133}.

\leavevmode\hypertarget{ref-Falcone2010}{}%
Falcone, James A., Daren M. Carlisle, and Lisa C. Weber. 2010. ``Quantifying human disturbance in watersheds: Variable selection and performance of a GIS-based disturbance index for predicting the biological condition of perennial streams.'' \emph{Ecol. Indic.} 10 (2): 264--73. \url{https://doi.org/10.1016/j.ecolind.2009.05.005}.

\leavevmode\hypertarget{ref-FAO2010}{}%
FAO. 2010. ``Global Forest Resources Assessment 2010.'' \emph{America (NY).} 147: 350 pp. \url{https://doi.org/https://doi.org/10.1787/agr_outlook-2016-en}.

\leavevmode\hypertarget{ref-Farr2007}{}%
Farr, Tom G., Paul A. Rosen, Edward Caro, Robert Crippen, Riley Duren, Scott Hensley, Michael Kobrick, et al. 2007. ``The Shuttle Radar Topography Mission.'' \emph{Rev. Geophys.} 45 (2): RG2004. \url{https://doi.org/10.1029/2005RG000183}.

\leavevmode\hypertarget{ref-Forman1996a}{}%
Forman, R. T. T., and A. M. Hersperger. 1996. ``Road ecology and road density in different landscapes, with international planning and mitigation solutions.'' \emph{Transp. Wildl. Reducing Wildl. Mortal. Improv. Wildl. Passageways Across Transp. Corridors}, 23. \url{http://trid.trb.org/view.aspx?id=475846}.

\leavevmode\hypertarget{ref-FunacaoCearencedeMeteorologiaeRecursosHidricos-FUNCEME2008a}{}%
Funação Cearence de Meteorologia e Recursos Hídricos - FUNCEME. 2008. ``Mapeamento dos espelhos d'água no Brasil.'' \url{http://www2.ana.gov.br/Paginas/servicos/cadastros/Barragens/MapeamentoEspelhosDagua.aspx}.

\leavevmode\hypertarget{ref-Guadagnin2010}{}%
Guadagnin, Demetrio Luis, Sergio Martin Zalba, Beatriz Costa Górriz, Carlos Roberto Fonseca, Ana Julia Nebbia, Yannina Andrea Cuevas, Carine Emer, et al. 2010. ``Árvores e arbustos exóticos invasores no Pampa: questões ecológicas, culturais e sócio-econômicas de um desafio crescente.'' In \emph{Campos Sulinos Conserv. E Uso Sustentável Da Biodiversidade}, 300--316. Brasilia.

\leavevmode\hypertarget{ref-Harding1998}{}%
Harding, J S, E F Benfield, P V Bolstad, G S Helfman, and E. B. D. Jones. 1998. ``Stream biodiversity: The ghost of land use past.'' \emph{Proc. Natl. Acad. Sci.} 95 (25): 14843--7. \url{https://doi.org/10.1073/pnas.95.25.14843}.

\leavevmode\hypertarget{ref-Hasenack}{}%
Hasenack, Heinrich, Eliseu Weber, Ilsi I. Boldrini, and Rafael Trevisan. n.d. ``Mapa de sistemas ecológicos do estado do Rio Grande do Sul.''

\leavevmode\hypertarget{ref-Hasenack2010b}{}%
Hasenack, Heinrich, and Eliseu (Org) Weber. 2010. ``Base cartográfica vetorial contínua do Rio Grande do Sul - escala 1:50.000.'' UFRGS-IB-Centro de Ecologia.

\leavevmode\hypertarget{ref-Heiner2011a}{}%
Heiner, Michael, Jonathan Higgins, Xinhai Li, and Barry Baker. 2011. ``Identifying freshwater conservation priorities in the Upper Yangtze River Basin.'' \emph{Freshw. Biol.} 56 (1): 89--105. \url{https://doi.org/10.1111/j.1365-2427.2010.02466.x}.

\leavevmode\hypertarget{ref-Herbst2012}{}%
Herbst, David B., Michael T. Bogan, Sandra K. Roll, and Hugh D. Safford. 2012. ``Effects of livestock exclusion on in-stream habitat and benthic invertebrate assemblages in montane streams.'' \emph{Freshw. Biol.} 57 (1): 204--17. \url{https://doi.org/10.1111/j.1365-2427.2011.02706.x}.

\leavevmode\hypertarget{ref-IBGE2004}{}%
IBGE. 2004. ``Mapa de Biomas do Brasil.'' \url{http://www.ibge.gov.br/home/presidencia/noticias/21052004biomashtml.shtm}.

\leavevmode\hypertarget{ref-IBGE2015}{}%
---------. 2015. ``Banco de Dados Agregados. Sistema IBGE de Recuperação Automática - SIDRA.'' \url{http://www.sidra.ibge.gov.br/}.

\leavevmode\hypertarget{ref-Jenkins2003}{}%
Jenkins, Martin. 2003. ``Prospects for Biodiversity.'' \emph{Science (80-. ).} 302 (5648): 1175--7. \url{https://doi.org/10.1126/science.1088666}.

\leavevmode\hypertarget{ref-Khoury2011a}{}%
Khoury, Mary, Jonathan Higgins, and Roy Weitzell. 2011. ``A freshwater conservation assessment of the Upper Mississippi River basin using a coarse- and fine-filter approach.'' \emph{Freshw. Biol.} 56 (1): 162--79. \url{https://doi.org/10.1111/j.1365-2427.2010.02468.x}.

\leavevmode\hypertarget{ref-Laliberte2010a}{}%
Laliberté, Etienne, and Pierre Legendre. 2010. ``A distance-based framework for measuring functional diversity from multiple traits.'' \emph{Ecology} 91 (1): 299--305. \url{https://doi.org/10.1890/08-2244.1}.

\leavevmode\hypertarget{ref-Laurance2013}{}%
Laurance, William F., and Andrew Balmford. 2013. ``A global map for road building.'' \emph{Nature} 495 (7441): 308--9. \url{https://doi.org/10.1038/495308a}.

\leavevmode\hypertarget{ref-Lavorel2007a}{}%
Lavorel, Sandra, Karl Grigulis, Sue McIntyre, Nick S G Williams, Denys Garden, Josh Dorrough, Sandra Berman, Fabien Quétier, Aurélie Thébault, and Anne Bonis. 2007. ``Assessing functional diversity in the field -- methodology matters!'' \emph{Funct. Ecol.} 22 (1): 071124124908001--??? \url{https://doi.org/10.1111/j.1365-2435.2007.01339.x}.

\leavevmode\hypertarget{ref-Ligeiro2013}{}%
Ligeiro, Raphael, Robert M. Hughes, Philip R. Kaufmann, Diego R. Macedo, Kele R. Firmiano, Wander R. Ferreira, Déborah Oliveira, Adriano S. Melo, and Marcos Callisto. 2013. ``Defining quantitative stream disturbance gradients and the additive role of habitat variation to explain macroinvertebrate taxa richness.'' \emph{Ecol. Indic.} 25 (April 2016): 45--57. \url{https://doi.org/10.1016/j.ecolind.2012.09.004}.

\leavevmode\hypertarget{ref-Linke2011c}{}%
Linke, Simon, Eren Turak, and Jeanne Nel. 2011. ``Freshwater conservation planning: the case for systematic approaches.'' \emph{Freshw. Biol.} 56 (1): 6--20. \url{https://doi.org/10.1111/j.1365-2427.2010.02456.x}.

\leavevmode\hypertarget{ref-Lourival2011a}{}%
Lourival, Reinaldo, Martin Drechsler, Matthew E. Watts, Edward T. Game, and Hugh P. Possingham. 2011. ``Planning for reserve adequacy in dynamic landscapes; maximizing future representation of vegetation communities under flood disturbance in the Pantanal wetland.'' \emph{Divers. Distrib.} 17 (2): 297--310. \url{https://doi.org/10.1111/j.1472-4642.2010.00722.x}.

\leavevmode\hypertarget{ref-Margules2000}{}%
Margules, C R, and R. L. Pressey. 2000. ``Systematic conservation planning.'' \emph{Nature} 405 (6783): 243--53. \url{https://doi.org/10.1038/35012251}.

\leavevmode\hypertarget{ref-Myers2000}{}%
Myers, Norman, Russell A. Mittermeier, Cristina G Mittermeier, Gustavo A. B. da Fonseca, and Jennifer Kent. 2000. ``Biodiversity hotspots for conservation priorities.'' \emph{Nature} 403 (6772): 853--58. \url{https://doi.org/10.1038/35002501}.

\leavevmode\hypertarget{ref-Nabinger2000}{}%
Nabinger, C, A. de Moraes, and G E Maraschin. 2000. ``Campos in Southern Brazil.'' In \emph{Grassl. Ecophysiol. Grazing Ecol.}, edited by G. Lemaire, J. Hodgson, A. de Moraes, C. Nabinger, and P. C. de F. Carvalho, 1996:355--76. New York, NY: CAB International.

\leavevmode\hypertarget{ref-Nardi2008}{}%
Nardi, Fernando, Salvatore Grimaldi, Monia Santini, Andrea Petroselli, and Lucio Ubertini. 2008. ``Hydrogeomorphic properties of simulated drainage patterns using digital elevation models: the flat area issue / Propriétés hydro-géomorphologiques de réseaux de drainage simulés à partir de modèles numériques de terrain: la question des zones planes.'' \emph{Hydrol. Sci. J.} 53 (6): 1176--93. \url{https://doi.org/10.1623/hysj.53.6.1176}.

\leavevmode\hypertarget{ref-Noss1983}{}%
Noss, Reed F. 1983. ``A Regional Landscape Approach to Maintain Diversity.'' \emph{Bioscience} 33 (11): 700--706. \url{https://doi.org/10.2307/1309350}.

\leavevmode\hypertarget{ref-Oksanen2016}{}%
Oksanen, Jari, F. Guillaume Blanchet, Michael Friendly, Roeland Kindt, Pierre Legendre, Dan McGlinn, Peter R. Minchin, et al. 2016. ``vegan: Community Ecology Package.'' \emph{R Packag. Version 2.4-0.} \url{https://cran.r-project.org/package=vegan}.

\leavevmode\hypertarget{ref-ONeill1997}{}%
O'Neill, Robert V, Carolyn T Hunsaker, K Bruce Jones, Kurt H Riitters, James D Wickham, Paul M Schwartz, Iris A Goodman, Barbara L Jackson, and William S Baillargeon. 1997. ``Monitoring Environmental Quality at the Landscape Scale.'' \emph{Bioscience} 47 (8): 513--19. \url{https://doi.org/10.2307/1313119}.

\leavevmode\hypertarget{ref-Overbeck2006}{}%
Overbeck, G E, S C Müller, V D Pillar, and J Pfadenhauer. 2006. ``Floristic composition, environmental variation and species distribution patterns in burned grassland in southern Brazil.'' \emph{Brazilian J. Biol.} 66 (4): 1073--90. \url{https://doi.org/10.1590/S1519-69842006000600015}.

\leavevmode\hypertarget{ref-Overbeck2007a}{}%
Overbeck, Gerhard Ernst, Sandra Cristina Müller, Alessandra Fidelis, Jörg Pfadenhauer, Valério De Patta Pillar, Carolina C. Blanco, Ilsi Iob Boldrini, Rogerio Both, and Eduardo D. Forneck. 2007. ``Brazil's neglected biome: The South Brazilian Campos.'' \emph{Perspect. Plant Ecol. Evol. Syst.} 9 (2): 101--16. \url{https://doi.org/10.1016/j.ppees.2007.07.005}.

\leavevmode\hypertarget{ref-Overbeck2005}{}%
Overbeck, Gerhard Ernst, Sandra Cristina Müller, Valério DePatta Pillar, and Jörg Pfadenhauer. 2005. ``Fine‐scale post‐fire dynamics in southern Brazilian subtropical grassland.'' \emph{J. Veg. Sci.} 16 (6): 655--64. \url{https://doi.org/10.1111/j.1654-1103.2005.tb02408.x}.

\leavevmode\hypertarget{ref-Poff2007}{}%
Poff, N Leroy, Julian D Olden, David M Merritt, and David M Pepin. 2007. ``Homogenization of regional river dynamics by dams and global biodiversity implications.'' \emph{Proc. Natl. Acad. Sci.} 104 (14): 5732--7. \url{https://doi.org/10.1073/pnas.0609812104}.

\leavevmode\hypertarget{ref-Postel1996}{}%
Postel, Sandra L., Gretchen C. Daily, and Paul R. Ehrlich. 1996. ``Human Appropriation of Renewable Fresh Water.'' \emph{Science (80-. ).} 271 (5250): 785--88. \url{https://doi.org/10.1126/science.271.5250.785}.

\leavevmode\hypertarget{ref-Pressey2007}{}%
Pressey, Robert L., Mar Cabeza, Matthew E. Watts, Richard M. Cowling, and Kerrie A. Wilson. 2007. ``Conservation planning in a changing world.'' \emph{Trends Ecol. Evol.} 22 (11): 583--92. \url{https://doi.org/10.1016/j.tree.2007.10.001}.

\leavevmode\hypertarget{ref-Ricciardi1999a}{}%
Ricciardi, Anthony, and Joseph B. Rasmussen. 1999. ``Extinction Rates of North American Freshwater Fauna.'' \emph{Conserv. Biol.} 13 (5): 1220--2. \url{https://doi.org/10.1046/j.1523-1739.1999.98380.x}.

\leavevmode\hypertarget{ref-RioGrandedoSul-SEPLAN2013a}{}%
Rio Grande do Sul - SEPLAN. 2013. ``Atlas Socioeconômico do Rio Grande do Sul.'' \url{http://www.atlassocioeconomico.rs.gov.br}.

\leavevmode\hypertarget{ref-Ripley2005a}{}%
Ripley, Travis, Garry Scrimgeour, and Mark S Boyce. 2005. ``Bull trout ( Salvelinus confluentus ) occurrence and abundance influenced by cumulative industrial developments in a Canadian boreal forest watershed.'' \emph{Can. J. Fish. Aquat. Sci.} 62 (11): 2431--42. \url{https://doi.org/10.1139/f05-150}.

\leavevmode\hypertarget{ref-Roth1996}{}%
Roth, Nancy E., J. David Allan, and Donna L. Erickson. 1996. ``Landscape influences on stream biotic integrity assessed at multiple spatial scales.'' \emph{Landsc. Ecol.} 11 (3): 141--56. \url{https://doi.org/10.1007/BF02447513}.

\leavevmode\hypertarget{ref-Sala2000a}{}%
Sala, Osvaldo E. 2000. ``Global Biodiversity Scenarios for the Year 2100.'' \emph{Science (80-. ).} 287 (5459): 1770--4. \url{https://doi.org/10.1126/science.287.5459.1770}.

\leavevmode\hypertarget{ref-Sanderson2002}{}%
Sanderson, Eric W., Malanding Jaiteh, Marc a. Levy, Kent H. Redford, Antoinette V. Wannebo, and Gillian Woolmer. 2002. ``The Human Footprint and the Last of the Wild.'' \emph{Bioscience} 52 (10): 891. \href{https://doi.org/10.1641/0006-3568(2002)052\%5B0891:thfatl\%5D2.0.co;2}{https://doi.org/10.1641/0006-3568(2002)052{[}0891:thfatl{]}2.0.co;2}.

\leavevmode\hypertarget{ref-Saly2009}{}%
Sály, Péter, Tibor Erős, Péter Takács, András Specziár, István Kiss, and Péter Bíró. 2009. ``Assemblage level monitoring of stream fishes: The relative efficiency of single-pass vs. double-pass electrofishing.'' \emph{Fish. Res.} 99 (3): 226--33. \url{https://doi.org/10.1016/j.fishres.2009.06.010}.

\leavevmode\hypertarget{ref-Scott2001}{}%
Scott, Mark C., and Gene S. Helfman. 2001. ``Native Invasions, Homogenization, and the Mismeasure of Integrity of Fish Assemblages.'' \emph{Fisheries} 26 (11): 6--15. \href{https://doi.org/10.1577/1548-8446(2001)026\%3C0006:NIHATM\%3E2.0.CO;2}{https://doi.org/10.1577/1548-8446(2001)026\textless{}0006:NIHATM\textgreater{}2.0.CO;2}.

\leavevmode\hypertarget{ref-Stein2002a}{}%
Stein, J.L, J.A Stein, and H.A Nix. 2002. ``Spatial analysis of anthropogenic river disturbance at regional and continental scales: identifying the wild rivers of Australia.'' \emph{Landsc. Urban Plan.} 60 (1): 1--25. \url{https://doi.org/10.1016/S0169-2046(02)00048-8}.

\leavevmode\hypertarget{ref-Stoddard2005a}{}%
Stoddard, John L. 2004. ``Use of Ecological Regions in Aquatic Assessments of Ecological Condition.'' \emph{Environ. Manage.} 34 (S1): S61--S70. \url{https://doi.org/10.1007/s00267-003-0193-0}.

\leavevmode\hypertarget{ref-Stoddard2006}{}%
Stoddard, John L., David P. Larsen, Charles P. Hawkins, Richard K. Johnson, and Richard H. Norris. 2006. ``Setting expectations for the ecological condition of streams: the concept of reference condition.'' \emph{Freshw. Bioassessment} 16 (August): 1267--76. \href{https://doi.org/https://doi.org/10.1890/1051-0761(2006)016\%5B1267:SEFTEC\%5D2.0.CO;2}{https://doi.org/https://doi.org/10.1890/1051-0761(2006)016{[}1267:SEFTEC{]}2.0.CO;2}.

\leavevmode\hypertarget{ref-RTeam2016}{}%
Team, R Core. 2016. ``R: A language and environment for statistical computing.'' R Foundation for Statistical Computing, Vienna, Austria.

\leavevmode\hypertarget{ref-Teixeira2015}{}%
Teixeira, Fernanda Zimmermann. 2015. ``Trilhando caminhos para avaliar padrões espaciais de mortalidade e fragmentação em rodovias.'' PhD thesis, Universidade Federal do Rio Grande do Sul. \url{https://www.lume.ufrgs.br/bitstream/handle/10183/131935/000979649.pdf?sequence=1}.

\leavevmode\hypertarget{ref-Trombulak2000}{}%
Trombulak, Stephen C, and Christopher A Frissell. 2000. ``Review of Ecological Effects of Roads on Terrestrial and Aquatic Communities.'' \emph{Conserv. Biol.} 14 (1): 18--30. \url{https://doi.org/10.1046/j.1523-1739.2000.99084.x}.

\leavevmode\hypertarget{ref-Tulloch2015}{}%
Tulloch, Vivitskaia JD, Ayesha IT Tulloch, Piero Visconti, Benjamin S. Halpern, James EM Watson, Megan C. Evans, Nancy A. Auerbach, et al. 2015. ``Why do we map threats? Linking threat mapping with actions to make better conservation decisions.'' \emph{Front. Ecol. Environ.} 13 (2): 91--99. \url{https://doi.org/10.1890/140022}.

\leavevmode\hypertarget{ref-Tulloch2013}{}%
Tulloch, Vivitskaia J., Hugh P Possingham, Stacy D Jupiter, Chris Roelfsema, Ayesha I T Tulloch, and Carissa J Klein. 2013. ``Incorporating uncertainty associated with habitat data in marine reserve design.'' \emph{Biol. Conserv.} 162 (June): 41--51. \url{https://doi.org/10.1016/j.biocon.2013.03.003}.

\leavevmode\hypertarget{ref-Turak2011c}{}%
Turak, Eren, Simon Ferrier, Tom Barrett, Edwina Mesley, Michael Drielsma, Glenn Manion, Gavin Doyle, Janet Stein, and Geoff Gordon. 2011. ``Planning for the persistence of river biodiversity: exploring alternative futures using process-based models.'' \emph{Freshw. Biol.} 56 (1): 39--56. \url{https://doi.org/10.1111/j.1365-2427.2009.02394.x}.

\leavevmode\hypertarget{ref-Vie2009}{}%
Vié, Jean-Christophe, Craig Hilton-Taylor, and Simon N. Stuart. 2009. \emph{Wildlife in a changing world}. Edited by Jean-Christophe Vié, Craig Hilton-Taylor, and Simon N. Stuart. Vol. 51. 2. IUCN. \url{https://doi.org/10.2305/IUCN.CH.2009.17.en}.

\leavevmode\hypertarget{ref-Villeger2008}{}%
Villéger, Sébastien, Norman W H Mason, and David Mouillot. 2008. ``New Multidimensional Functional Diversity Indices for A Multifaceted Framework in Functional Ecology.'' \emph{Ecology} 89 (8): 2290--2301. \url{https://doi.org/10.1890/07-1206.1}.

\leavevmode\hypertarget{ref-Vinet2016}{}%
Vinet, Luc, and Alexei Zhedanov. 2016. \emph{OECD-FAO Agricultural Outlook 2016-2025}. OECD-Fao Agricultural Outlook. Paris: OECD. \url{https://doi.org/10.1787/agr_outlook-2016-en}.

\leavevmode\hypertarget{ref-Vorosmarty2010}{}%
Vörösmarty, C J, P B McIntyre, M O Gessner, D Dudgeon, A Prusevich, P Green, S Glidden, et al. 2010. ``Global threats to human water security and river biodiversity.'' \emph{Nature} 467 (7315): 555--61. \url{https://doi.org/10.1038/nature09440}.

\leavevmode\hypertarget{ref-Wiens2002}{}%
Wiens, John A. 2002. ``Riverine landscapes: taking landscape ecology into the water.'' \emph{Freshw. Biol.} 47 (4): 501--15. \url{https://doi.org/10.1046/j.1365-2427.2002.00887.x}.

\leavevmode\hypertarget{ref-Wilson2012}{}%
Wilson, J. Bastow, Robert K. Peet, Jürgen Dengler, and Meelis Pärtel. 2012. ``Plant species richness: the world records.'' Edited by Michael Palmer. \emph{J. Veg. Sci.} 23 (4): 796--802. \url{https://doi.org/10.1111/j.1654-1103.2012.01400.x}.

\leavevmode\hypertarget{ref-Zhang2014}{}%
Zhang, Haiping, and Liding Chen. 2014. ``Using the Ecological Risk Index Based on Combined Watershed and Administrative Boundaries to Assess Human Disturbances on River Ecosystems.'' \emph{Hum. Ecol. Risk Assess. An Int. J.} 20 (6): 1590--1607. \url{https://doi.org/10.1080/10807039.2013.842746}.

% ----------------------------------------------------------
% ELEMENTOS PÓS-TEXTUAIS
% ----------------------------------------------------------
\postextual

% ----------------------------------------------------------

% ----------------------------------------------------------
% Referências bibliográficas
% ----------------------------------------------------------
%\bibliography{dissertacaofinal}
% ----------------------------------------------------------
% Glossário
% ----------------------------------------------------------
%
% Consulte o manual da classe abntex2 para orientações sobre o glossário.
%
%\glossary

% ----------------------------------------------------------
% Apêndices
% ----------------------------------------------------------

% ---
% Inicia os apêndices
% ---
\beginsupplement
\input{C:/SIG/laboratorio/01_mestrado/dissertacao2019/front-and-back-matter/99_apendices.tex}
% Imprime uma página indicando o início dos apêndices
%\partapendices


% ---

% 
% % ----------------------------------------------------------
% % Anexos
% % ----------------------------------------------------------
% 
% % ---
% % Inicia os anexos
% % ---
% \begin{anexosenv}
% 
% % Imprime uma página indicando o início dos anexos
% \partanexos
% 
% % ---
% \chapter{Morbi ultrices rutrum lorem.}
% % ---
% \lipsum[30]
% 
% % ---
% \chapter{Cras non urna sed feugiat cum sociis natoque penatibus et magnis dis
% parturient montes nascetur ridiculus mus}
% % ---
% 
% \lipsum[31]
% 
% % ---
% \chapter{Fusce facilisis lacinia dui}
% % ---
% 
% \lipsum[32]
% 
% \end{anexosenv}
% 
% %---------------------------------------------------------------------
% % INDICE REMISSIVO
% %---------------------------------------------------------------------
% \phantompart
% \printindex
% %---------------------------------------------------------------------

\end{document}
